[functions.fib-subscription-payment]
verify_jwt = false

[functions.customer-read-link]
verify_jwt = false

[functions.customer-push]
verify_jwt = false

[functions.customer-push-manifest]
verify_jwt = false

[functions.customer-push-worker]
verify_jwt = false


[functions.debt-restore-admin]
verify_jwt = false

[functions.daftar-sync]
verify_jwt = false

[functions.daftar-sync-gateway]
verify_jwt = false
