import {createClient} from "npm:@supabase/supabase-js@2.116.0";
import {PDFDocument,rgb} from "npm:pdf-lib@1.17.1";
import fontkit from "npm:@pdf-lib/fontkit@1.1.1";
const env=(n:string)=>(Deno.env.get(n)??"").trim();
const key=()=>env("SUPABASE_SERVICE_ROLE_KEY")||(()=>{try{const x=JSON.parse(env("SUPABASE_SECRET_KEYS"));return String(x.default??Object.values(x)[0]??"");}catch{return "";}})();
async function sh(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,"0")).join("");}
async function token(a:any){const e=env("TELEGRAM_BOT_TOKEN");if(e)return e;const r=await a.rpc("get_telegram_runtime_config_service");const x=Array.isArray(r.data)?r.data[0]:r.data;return String(x?.bot_token??"").trim();}
const clean=(v:unknown)=>String(v??"").replace(/[\r\n\t]+/g," ").replace(/\s+/g," ").trim();
const money=(v:unknown,c:unknown)=>{const n=Number(v??0),x=Number.isFinite(n)?n:0;return String(c??"IQD").toUpperCase()==="USD"?`$${x.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`:`${Math.round(x).toLocaleString("en-US")} د.ع`;};
const date=(v:unknown)=>new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Baghdad",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(String(v)));
async function makePdf(ctx:any){const fr=await fetch("https://raw.githubusercontent.com/google/fonts/main/ofl/notosansarabic/NotoSansArabic%5Bwdth%2Cwght%5D.ttf");if(!fr.ok)throw new Error("font_failed");const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);const f=await pdf.embedFont(new Uint8Array(await fr.arrayBuffer()),{subset:true});const p=pdf.addPage([595.28,841.89]);let y=782;const r=(t:string,s=10)=>{const z=clean(t),w=f.widthOfTextAtSize(z,s);p.drawText(z,{x:Math.max(42,553-w),y,size:s,font:f,color:rgb(.06,.06,.06)});};const d=(n:number)=>y-=n;r("پسووڵەی مامەڵە - ZHIROX",18);d(30);r(`مارکێت: ${ctx.market}`,10);d(18);r(`کڕیار: ${ctx.customer}`,10);d(22);r(`جۆر: ${ctx.type==="payment_created"?"پارەدان":"قەرز"}`,11);d(18);r(`بڕ: ${money(ctx.amount,ctx.currency)}`,12);d(18);r(`کات: ${date(ctx.time)}`,9);d(18);r(`قەرزی ماوە: ${money(ctx.remaining,"IQD")}`,10);d(18);if(ctx.receipt){r(`ژمارەی پسووڵە: ${ctx.receipt}`,9);d(18);}if(ctx.note){r(`تێبینی: ${clean(ctx.note).slice(0,160)}`,8.5);d(18);}r("ئەم پسووڵەیە لە سیستەمی ZHIROX دەرکراوە.",8.5);return await pdf.save({useObjectStreams:true});}
async function send(t:string,chat:string,b:Uint8Array,name:string,cap:string){const f=new FormData();f.append("chat_id",chat);f.append("caption",cap);f.append("document",new Blob([b],{type:"application/pdf"}),name);const r=await fetch(`https://api.telegram.org/bot${t}/sendDocument`,{method:"POST",body:f});const j=await r.json();if(!r.ok||j?.ok!==true)throw new Error(String(j?.description??"send_failed"));return j.result;}
Deno.serve(async(req)=>{if(req.method!=="POST")return new Response("method",{status:405});const a=createClient(env("SUPABASE_URL"),key(),{auth:{persistSession:false,autoRefreshToken:false}}),bt=await token(a);if(!bt)return new Response("config",{status:503});const expected=await sh(`${bt}:customer-pdf`);if((req.headers.get("x-zhirox-telegram-internal")??"")!==expected)return new Response("forbidden",{status:401});const b=await req.json(),chat=String(b.chat_id??""),type=String(b.event_type??""),id=String(b.event_record_id??"");if(!chat||!["debt_created","payment_created"].includes(type)||!id)return new Response("input",{status:400});const s=await a.rpc("get_telegram_customer_snapshot_service",{p_chat_id:chat});if(s.error||!s.data)return new Response("linked",{status:404});const cur=s.data as any,p=b.payload??{};let note="",receipt="";if(type==="debt_created"){const q=await a.from("debts").select("id,customer_id,description").eq("id",id).eq("customer_id",cur.customer_id).eq("is_deleted",false).maybeSingle();if(!q.data)return new Response("event",{status:404});note=String(q.data.description??"");const rr=await a.from("receipt_documents").select("receipt_number").eq("admin_id",cur.market_id).eq("source_type","debt").eq("source_id",id).order("created_at",{ascending:false}).limit(1);receipt=String(rr.data?.[0]?.receipt_number??"");}else{const q=await a.from("payments").select("id,debt_id,note").eq("id",id).maybeSingle();if(q.data){const d=await a.from("debts").select("customer_id").eq("id",q.data.debt_id).eq("customer_id",cur.customer_id).maybeSingle();if(!d.data)return new Response("event",{status:404});note=String(q.data.note??"");const rr=await a.from("receipt_documents").select("receipt_number").eq("admin_id",cur.market_id).eq("source_type","payment").eq("source_id",id).order("created_at",{ascending:false}).limit(1);receipt=String(rr.data?.[0]?.receipt_number??"");}else{const g=await a.from("customer_general_payments").select("id,note").eq("id",id).eq("customer_id",cur.customer_id).maybeSingle();if(!g.data)return new Response("event",{status:404});note=String(g.data.note??"");}}
const ctx={market:cur.market_name,customer:cur.customer_name,type,amount:p.amount,currency:p.currency,remaining:p.remaining_iqd??cur.remaining_iqd,time:p.occurred_at??new Date().toISOString(),note,receipt};const bytes=await makePdf(ctx);const res=await send(bt,chat,bytes,`ZHIROX-receipt-${id.slice(0,8)}.pdf`,`🧾 پسووڵەی خۆکار • ${money(ctx.amount,ctx.currency)}`);return new Response(JSON.stringify({ok:true,sent:true,message_id:res?.message_id??null}),{headers:{"content-type":"application/json"}});});