import 'package:flutter/material.dart';

class AdditionalEmployeePermissionSpec {
  const AdditionalEmployeePermissionSpec({
    required this.key,
    required this.title,
    required this.group,
  });

  final String key;
  final String title;
  final String group;

  IconData get icon => switch (group) {
    'کڕیار و بەڵگە' => Icons.people_outline,
    'قەرز و پەسەندکردن' => Icons.receipt_long_outlined,
    'پارەدانەوە' => Icons.payments_outlined,
    'پسووڵە' => Icons.receipt_outlined,
    'کارمەند' => Icons.badge_outlined,
    'Sync و Backup' => Icons.sync,
    'ئاسایش و چوونەژوورەوە' => Icons.security_outlined,
    'مامەڵە دارایی' => Icons.swap_horiz,
    'ڕاپۆرتی پێشکەوتوو' => Icons.analytics_outlined,
    'CRM و Follow-up' => Icons.people_outline,
    'سیستەم و DevOps' => Icons.settings_outlined,
    'پەسەندکردن' => Icons.verified_outlined,
    'Privacy و زانیاری نهێنی' => Icons.privacy_tip_outlined,
    'ئاگادارکردنەوە و پەیام' => Icons.notifications_outlined,
    'API و Integration' => Icons.link_outlined,
    _ => Icons.settings_outlined,
  };
}

const additionalEmployeePermissionSpecs = <AdditionalEmployeePermissionSpec>[
  AdditionalEmployeePermissionSpec(key: 'can_view_customer_documents', title: 'بینینی بەڵگەنامەکانی کڕیار', group: 'کڕیار و بەڵگە'),
  AdditionalEmployeePermissionSpec(key: 'can_manage_customer_documents', title: 'بەڕێوەبردنی بەڵگەنامەکانی کڕیار', group: 'کڕیار و بەڵگە'),
  AdditionalEmployeePermissionSpec(key: 'can_create_customer_qr', title: 'دروستکردنی QR ـی کڕیار', group: 'کڕیار و بەڵگە'),
  AdditionalEmployeePermissionSpec(key: 'can_view_customer_qr', title: 'بینینی QR ـی کڕیار', group: 'کڕیار و بەڵگە'),
  AdditionalEmployeePermissionSpec(key: 'can_archive_customers', title: 'ئەرشیڤکردنی کڕیار', group: 'کڕیار و بەڵگە'),
  AdditionalEmployeePermissionSpec(key: 'can_restore_archived_customers', title: 'گەڕاندنەوەی کڕیار لە ئەرشیڤ', group: 'کڕیار و بەڵگە'),
  AdditionalEmployeePermissionSpec(key: 'can_blacklist_customers', title: 'خستنە Blacklist', group: 'کڕیار و بەڵگە'),
  AdditionalEmployeePermissionSpec(key: 'can_remove_customer_blacklist', title: 'لابردن لە Blacklist', group: 'کڕیار و بەڵگە'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_new_debts', title: 'پەسەندکردنی قەرزی نوێ', group: 'قەرز و پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_reject_new_debts', title: 'ڕەتکردنەوەی قەرزی نوێ', group: 'قەرز و پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_override_debt_limit', title: 'تێپەڕاندنی سنووری قەرز', group: 'قەرز و پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_change_due_date_after_create', title: 'گۆڕینی بەرواری دانەوە دوای تۆمارکردن', group: 'قەرز و پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_close_debts', title: 'داخستنی قەرز بە دەستی', group: 'قەرز و پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_reopen_debts', title: 'کردنەوەی قەرزی داخراو', group: 'قەرز و پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_change_debt_currency', title: 'گۆڕینی دراوی مامەڵە', group: 'قەرز و پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_change_debt_amount_after_approval', title: 'گۆڕینی بڕی قەرز دوای پەسەندکردن', group: 'قەرز و پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_payments', title: 'پەسەندکردنی پارەدانەوە', group: 'پارەدانەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_void_payments', title: 'هەڵوەشاندنەوەی پارەدانەوە', group: 'پارەدانەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_correct_payment_amount', title: 'چاککردنەوەی بڕی پارەدانەوە', group: 'پارەدانەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_correct_payment_date', title: 'چاککردنەوەی بەرواری پارەدانەوە', group: 'پارەدانەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_reallocate_payments', title: 'گواستنەوەی پارەدانەوە بۆ مامەڵەی تر', group: 'پارەدانەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_restore_voided_payments', title: 'گەڕاندنەوەی پارەدانەوەی هەڵوەشێنراو', group: 'پارەدانەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_print_receipts', title: 'چاپکردنی پسووڵە', group: 'پسووڵە'),
  AdditionalEmployeePermissionSpec(key: 'can_share_receipts', title: 'هاوبەشکردنی پسووڵە', group: 'پسووڵە'),
  AdditionalEmployeePermissionSpec(key: 'can_reissue_receipts', title: 'دووبارە دەرکردنی پسووڵە', group: 'پسووڵە'),
  AdditionalEmployeePermissionSpec(key: 'can_view_receipt_history', title: 'بینینی مێژووی پسووڵەکان', group: 'پسووڵە'),
  AdditionalEmployeePermissionSpec(key: 'can_lock_receipts', title: 'قوفڵکردنی پسووڵە دوای دەرکردن', group: 'پسووڵە'),
  AdditionalEmployeePermissionSpec(key: 'can_unlock_receipts', title: 'هەڵکردنەوەی قوفڵی پسووڵە', group: 'پسووڵە'),
  AdditionalEmployeePermissionSpec(key: 'can_suspend_employees', title: 'وەستاندنی کارمەند', group: 'کارمەند'),
  AdditionalEmployeePermissionSpec(key: 'can_reactivate_employees', title: 'چالاککردنەوەی کارمەند', group: 'کارمەند'),
  AdditionalEmployeePermissionSpec(key: 'can_reset_employee_passwords', title: 'Reset کردنی وشەی نهێنی کارمەند', group: 'کارمەند'),
  AdditionalEmployeePermissionSpec(key: 'can_view_employee_login_history', title: 'بینینی مێژووی چوونەژوورەوەی کارمەند', group: 'کارمەند'),
  AdditionalEmployeePermissionSpec(key: 'can_force_employee_logout', title: 'دەرکردنی زۆرەملێی کارمەند لە هەموو ئامێرەکان', group: 'کارمەند'),
  AdditionalEmployeePermissionSpec(key: 'can_manage_employee_devices', title: 'بەڕێوەبردنی ئامێرە ڕێگەپێدراوەکان', group: 'کارمەند'),
  AdditionalEmployeePermissionSpec(key: 'can_pause_sync', title: 'وەستاندنی Sync', group: 'Sync و Backup'),
  AdditionalEmployeePermissionSpec(key: 'can_resume_sync', title: 'دەستپێکردنەوەی Sync', group: 'Sync و Backup'),
  AdditionalEmployeePermissionSpec(key: 'can_replay_failed_sync', title: 'Replay کردنی Sync ـی شکستخواردوو', group: 'Sync و Backup'),
  AdditionalEmployeePermissionSpec(key: 'can_view_sync_payloads', title: 'بینینی وردەکاری Payload ـی Sync', group: 'Sync و Backup'),
  AdditionalEmployeePermissionSpec(key: 'can_download_backups', title: 'داگرتنی Backup', group: 'Sync و Backup'),
  AdditionalEmployeePermissionSpec(key: 'can_export_audit_log', title: 'Export کردنی Audit Log', group: 'Sync و Backup'),
  AdditionalEmployeePermissionSpec(key: 'can_view_active_devices', title: 'بینینی ئامێرە چالاکەکان', group: 'ئاسایش و چوونەژوورەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_remove_trusted_devices', title: 'سڕینەوەی ئامێری مۆڵەتپێدراو', group: 'ئاسایش و چوونەژوورەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_new_devices', title: 'ڕێگەدان بە ئامێری نوێ', group: 'ئاسایش و چوونەژوورەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_view_failed_logins', title: 'بینینی چوونەژوورەوە شکستخواردووەکان', group: 'ئاسایش و چوونەژوورەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_lock_employee_accounts', title: 'قوفڵکردنی هەژماری کارمەند', group: 'ئاسایش و چوونەژوورەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_unlock_employee_accounts', title: 'هەڵکردنەوەی قوفڵی هەژمار', group: 'ئاسایش و چوونەژوورەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_force_password_change', title: 'ناچارکردنی گۆڕینی وشەی نهێنی', group: 'ئاسایش و چوونەژوورەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_manage_biometric_login', title: 'بەڕێوەبردنی Biometric Login', group: 'ئاسایش و چوونەژوورەوە'),
  AdditionalEmployeePermissionSpec(key: 'can_view_deleted_transactions', title: 'بینینی مامەڵە سڕاوەکان', group: 'مامەڵە دارایی'),
  AdditionalEmployeePermissionSpec(key: 'can_restore_deleted_transactions', title: 'گەڕاندنەوەی مامەڵەی سڕاوە', group: 'مامەڵە دارایی'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_transaction_edits', title: 'پەسەندکردنی دەستکاری مامەڵە', group: 'مامەڵە دارایی'),
  AdditionalEmployeePermissionSpec(key: 'can_view_transaction_change_history', title: 'بینینی مێژووی گۆڕانکاری مامەڵە', group: 'مامەڵە دارایی'),
  AdditionalEmployeePermissionSpec(key: 'can_lock_old_transactions', title: 'قوفڵکردنی مامەڵە کۆنەکان', group: 'مامەڵە دارایی'),
  AdditionalEmployeePermissionSpec(key: 'can_unlock_old_transactions', title: 'هەڵکردنەوەی قوفڵی مامەڵە', group: 'مامەڵە دارایی'),
  AdditionalEmployeePermissionSpec(key: 'can_transfer_transactions_between_customers', title: 'گواستنەوەی مامەڵە بۆ کڕیارێکی تر', group: 'مامەڵە دارایی'),
  AdditionalEmployeePermissionSpec(key: 'can_require_transaction_edit_reason', title: 'دانانی هۆکاری پێویست بۆ دەستکاری مامەڵە', group: 'مامەڵە دارایی'),
  AdditionalEmployeePermissionSpec(key: 'can_view_daily_reports', title: 'بینینی ڕاپۆرتی ڕۆژانە', group: 'ڕاپۆرتی پێشکەوتوو'),
  AdditionalEmployeePermissionSpec(key: 'can_view_weekly_reports', title: 'بینینی ڕاپۆرتی هەفتانە', group: 'ڕاپۆرتی پێشکەوتوو'),
  AdditionalEmployeePermissionSpec(key: 'can_view_monthly_reports', title: 'بینینی ڕاپۆرتی مانگانە', group: 'ڕاپۆرتی پێشکەوتوو'),
  AdditionalEmployeePermissionSpec(key: 'can_view_yearly_reports', title: 'بینینی ڕاپۆرتی ساڵانە', group: 'ڕاپۆرتی پێشکەوتوو'),
  AdditionalEmployeePermissionSpec(key: 'can_create_custom_reports', title: 'دروستکردنی ڕاپۆرتی تایبەت', group: 'ڕاپۆرتی پێشکەوتوو'),
  AdditionalEmployeePermissionSpec(key: 'can_schedule_reports', title: 'خشتەکردنی ڕاپۆرت', group: 'ڕاپۆرتی پێشکەوتوو'),
  AdditionalEmployeePermissionSpec(key: 'can_send_report_notifications', title: 'ناردنی ڕاپۆرت بە ئاگادارکردنەوە', group: 'ڕاپۆرتی پێشکەوتوو'),
  AdditionalEmployeePermissionSpec(key: 'can_view_employee_performance_reports', title: 'بینینی ڕاپۆرتی کارایی کارمەندان', group: 'ڕاپۆرتی پێشکەوتوو'),
  AdditionalEmployeePermissionSpec(key: 'can_assign_customer_tags', title: 'دانانی Tag بۆ کڕیار', group: 'CRM و Follow-up'),
  AdditionalEmployeePermissionSpec(key: 'can_manage_customer_tags', title: 'بەڕێوەبردنی Tag ـەکان', group: 'CRM و Follow-up'),
  AdditionalEmployeePermissionSpec(key: 'can_set_customer_priority', title: 'دانانی Priority بۆ کڕیار', group: 'CRM و Follow-up'),
  AdditionalEmployeePermissionSpec(key: 'can_set_customer_status', title: 'دانانی دۆخی تایبەت بۆ کڕیار', group: 'CRM و Follow-up'),
  AdditionalEmployeePermissionSpec(key: 'can_create_followups', title: 'دروستکردنی Follow-up', group: 'CRM و Follow-up'),
  AdditionalEmployeePermissionSpec(key: 'can_complete_followups', title: 'تەواوکردنی Follow-up', group: 'CRM و Follow-up'),
  AdditionalEmployeePermissionSpec(key: 'can_view_customer_contact_history', title: 'بینینی مێژووی پەیوەندی لەگەڵ کڕیار', group: 'CRM و Follow-up'),
  AdditionalEmployeePermissionSpec(key: 'can_add_private_customer_notes', title: 'زیادکردنی تێبینی تایبەت بۆ کڕیار', group: 'CRM و Follow-up'),
  AdditionalEmployeePermissionSpec(key: 'can_view_backend_health', title: 'بینینی دۆخی Backend', group: 'سیستەم و DevOps'),
  AdditionalEmployeePermissionSpec(key: 'can_view_database_health', title: 'بینینی دۆخی Database', group: 'سیستەم و DevOps'),
  AdditionalEmployeePermissionSpec(key: 'can_view_sync_queue', title: 'بینینی Sync Queue', group: 'سیستەم و DevOps'),
  AdditionalEmployeePermissionSpec(key: 'can_clear_cache', title: 'پاککردنەوەی Cache', group: 'سیستەم و DevOps'),
  AdditionalEmployeePermissionSpec(key: 'can_refresh_configuration', title: 'نوێکردنەوەی Configuration', group: 'سیستەم و DevOps'),
  AdditionalEmployeePermissionSpec(key: 'can_view_version_history', title: 'بینینی Version History', group: 'سیستەم و DevOps'),
  AdditionalEmployeePermissionSpec(key: 'can_view_feature_flags', title: 'بینینی Feature Flags', group: 'سیستەم و DevOps'),
  AdditionalEmployeePermissionSpec(key: 'can_manage_feature_flags', title: 'بەڕێوەبردنی Feature Flags', group: 'سیستەم و DevOps'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_customer_creation', title: 'پەسەندکردنی زیادکردنی کڕیار', group: 'پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_customer_edits', title: 'پەسەندکردنی دەستکاری کڕیار', group: 'پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_customer_deletion', title: 'پەسەندکردنی سڕینەوەی کڕیار', group: 'پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_debt_edits', title: 'پەسەندکردنی دەستکاری قەرز', group: 'پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_debt_deletion', title: 'پەسەندکردنی سڕینەوەی قەرز', group: 'پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_payment_voids', title: 'پەسەندکردنی هەڵوەشاندنەوەی پارەدانەوە', group: 'پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_restores', title: 'پەسەندکردنی Restore', group: 'پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_debt_limit_changes', title: 'پەسەندکردنی گۆڕینی سنووری قەرز', group: 'پەسەندکردن'),
  AdditionalEmployeePermissionSpec(key: 'can_view_full_phone_numbers', title: 'بینینی ژمارەی تەلەفۆن بە تەواوی', group: 'Privacy و زانیاری نهێنی'),
  AdditionalEmployeePermissionSpec(key: 'can_view_masked_phone_numbers', title: 'بینینی ژمارەی Mask کراو', group: 'Privacy و زانیاری نهێنی'),
  AdditionalEmployeePermissionSpec(key: 'can_view_identity_documents', title: 'بینینی بەڵگە ناسنامەییەکان', group: 'Privacy و زانیاری نهێنی'),
  AdditionalEmployeePermissionSpec(key: 'can_download_identity_documents', title: 'داگرتنی بەڵگە ناسنامەییەکان', group: 'Privacy و زانیاری نهێنی'),
  AdditionalEmployeePermissionSpec(key: 'can_view_private_notes', title: 'بینینی Private Notes', group: 'Privacy و زانیاری نهێنی'),
  AdditionalEmployeePermissionSpec(key: 'can_edit_private_notes', title: 'دەستکاریکردنی Private Notes', group: 'Privacy و زانیاری نهێنی'),
  AdditionalEmployeePermissionSpec(key: 'can_export_personal_data', title: 'هەناردەکردنی زانیاری کەسی', group: 'Privacy و زانیاری نهێنی'),
  AdditionalEmployeePermissionSpec(key: 'can_anonymize_customer_data', title: 'ناسنامەنەماکردنی زانیاری کڕیار', group: 'Privacy و زانیاری نهێنی'),
  AdditionalEmployeePermissionSpec(key: 'can_send_sms', title: 'ناردنی SMS', group: 'ئاگادارکردنەوە و پەیام'),
  AdditionalEmployeePermissionSpec(key: 'can_send_push_notifications', title: 'ناردنی Push Notification', group: 'ئاگادارکردنەوە و پەیام'),
  AdditionalEmployeePermissionSpec(key: 'can_send_telegram_notifications', title: 'ناردنی Telegram', group: 'ئاگادارکردنەوە و پەیام'),
  AdditionalEmployeePermissionSpec(key: 'can_send_whatsapp_templates', title: 'ناردنی WhatsApp Template', group: 'ئاگادارکردنەوە و پەیام'),
  AdditionalEmployeePermissionSpec(key: 'can_approve_notifications', title: 'پەسەندکردنی ئاگادارکردنەوە پێش ناردن', group: 'ئاگادارکردنەوە و پەیام'),
  AdditionalEmployeePermissionSpec(key: 'can_view_notification_delivery_status', title: 'بینینی Delivery Status', group: 'ئاگادارکردنەوە و پەیام'),
  AdditionalEmployeePermissionSpec(key: 'can_retry_failed_notifications', title: 'دووبارە ناردنەوەی ئاگادارکردنەوەی شکستخواردوو', group: 'ئاگادارکردنەوە و پەیام'),
  AdditionalEmployeePermissionSpec(key: 'can_lock_bulk_messaging', title: 'قوفڵکردنی Bulk Messaging', group: 'ئاگادارکردنەوە و پەیام'),
  AdditionalEmployeePermissionSpec(key: 'can_view_api_status', title: 'بینینی API Status', group: 'API و Integration'),
  AdditionalEmployeePermissionSpec(key: 'can_manage_api_keys', title: 'بەڕێوەبردنی API Keys', group: 'API و Integration'),
  AdditionalEmployeePermissionSpec(key: 'can_revoke_api_keys', title: 'Revoke کردنی API Key', group: 'API و Integration'),
  AdditionalEmployeePermissionSpec(key: 'can_view_webhook_logs', title: 'بینینی Webhook Logs', group: 'API و Integration'),
  AdditionalEmployeePermissionSpec(key: 'can_retry_webhooks', title: 'Retry کردنی Webhook', group: 'API و Integration'),
  AdditionalEmployeePermissionSpec(key: 'can_disable_integrations', title: 'قوفڵکردنی Integration', group: 'API و Integration'),
  AdditionalEmployeePermissionSpec(key: 'can_enable_integrations', title: 'چالاککردنی Integration', group: 'API و Integration'),
  AdditionalEmployeePermissionSpec(key: 'can_view_sync_mappings', title: 'بینینی Sync Mapping', group: 'API و Integration'),
  AdditionalEmployeePermissionSpec(key: 'can_create_automation_rules', title: 'دروستکردنی Automation Rule', group: 'Automation و Alert'),
  AdditionalEmployeePermissionSpec(key: 'can_edit_automation_rules', title: 'دەستکاریکردنی Automation Rule', group: 'Automation و Alert'),
  AdditionalEmployeePermissionSpec(key: 'can_delete_automation_rules', title: 'سڕینەوەی Automation Rule', group: 'Automation و Alert'),
  AdditionalEmployeePermissionSpec(key: 'can_pause_resume_automation', title: 'وەستاندن/دەستپێکردنەوەی Automation', group: 'Automation و Alert'),
  AdditionalEmployeePermissionSpec(key: 'can_view_automation_logs', title: 'بینینی Automation Logs', group: 'Automation و Alert'),
  AdditionalEmployeePermissionSpec(key: 'can_create_alert_rules', title: 'دروستکردنی Alert Rule', group: 'Automation و Alert'),
  AdditionalEmployeePermissionSpec(key: 'can_edit_alert_thresholds', title: 'دەستکاریکردنی Alert Threshold', group: 'Automation و Alert'),
  AdditionalEmployeePermissionSpec(key: 'can_mute_alerts', title: 'Mute/Unmute کردنی Alert', group: 'Automation و Alert'),
];

Map<String, bool> newAdditionalEmployeePermissionState() => {
  for (final spec in additionalEmployeePermissionSpecs) spec.key: false,
};
