enum OwnerPermissionScope { platform, market, admin }

class OwnerPermissionDefinition {
  const OwnerPermissionDefinition(this.key, this.label, this.groupKey, this.groupLabel, this.riskLevel, this.scopes, {this.requiresReason = false, this.requiresReauth = false, this.requiresTypedConfirmation = false, this.requiresTwoPersonApproval = false});
  final String key;
  final String label;
  final String groupKey;
  final String groupLabel;
  final int riskLevel;
  final Set<OwnerPermissionScope> scopes;
  final bool requiresReason;
  final bool requiresReauth;
  final bool requiresTypedConfirmation;
  final bool requiresTwoPersonApproval;
}

const ownerPermissionDefinitions = <OwnerPermissionDefinition>[
  OwnerPermissionDefinition('owner_access_console', 'چوونە ناو کۆنترۆڵی Owner', 'core', 'بنەڕەتی Owner', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_platform_dashboard', 'بینینی داشبۆردی پلاتفۆرم', 'core', 'بنەڕەتی Owner', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_platform_metrics', 'بینینی پێوانەکانی پلاتفۆرم', 'core', 'بنەڕەتی Owner', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_all_markets', 'بینینی هەموو مارکێتەکان', 'core', 'بنەڕەتی Owner', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_all_admins', 'بینینی هەموو بەڕێوەبەران', 'core', 'بنەڕەتی Owner', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_search_markets', 'گەڕان لە مارکێتەکان', 'core', 'بنەڕەتی Owner', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_search_admins', 'گەڕان لە بەڕێوەبەران', 'core', 'بنەڕەتی Owner', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_platform_activity', 'بینینی چالاکی پلاتفۆرم', 'core', 'بنەڕەتی Owner', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_create_admin', 'دروستکردنی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 2, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_view_admin_profile', 'بینینی پڕۆفایلی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 1, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_edit_admin_name', 'گۆڕینی ناوی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 2, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_edit_admin_phone', 'گۆڕینی ژمارەی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 2, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_edit_admin_email', 'گۆڕینی ئیمەیڵی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 2, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_change_admin_market', 'گواستنەوەی بەڕێوەبەر بۆ مارکێتی تر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_reset_admin_password', 'ڕێکخستنەوەی وشەی نهێنی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_force_admin_password_change', 'ناچارکردنی گۆڕینی وشەی نهێنی', 'admin_accounts', 'هەژماری بەڕێوەبەر', 2, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_lock_admin_login', 'قوفڵکردنی چوونەژوورەوەی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_unlock_admin_login', 'کردنەوەی قوفڵی چوونەژوورەوە', 'admin_accounts', 'هەژماری بەڕێوەبەر', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_suspend_admin', 'ڕاگرتنی هەژماری بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_activate_admin', 'چالاککردنەوەی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 2, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_archive_admin', 'ئەرشیڤکردنی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_restore_admin', 'گەڕاندنەوەی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_delete_admin', 'سڕینەوەی کۆتایی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 4, <OwnerPermissionScope>{OwnerPermissionScope.admin}, requiresReason: true, requiresReauth: true, requiresTypedConfirmation: true, requiresTwoPersonApproval: true),
  OwnerPermissionDefinition('owner_view_admin_last_login', 'بینینی کۆتا چوونەژوورەوە', 'admin_accounts', 'هەژماری بەڕێوەبەر', 1, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_view_admin_login_history', 'بینینی مێژووی چوونەژوورەوە', 'admin_accounts', 'هەژماری بەڕێوەبەر', 1, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_view_admin_devices', 'بینینی ئامێرەکانی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 1, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_revoke_admin_device', 'لابردنی مۆڵەتی ئامێری بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_revoke_admin_sessions', 'دەرکردنی بەڕێوەبەر لە هەموو session ـەکان', 'admin_accounts', 'هەژماری بەڕێوەبەر', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_verify_admin', 'پشتڕاستکردنەوەی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 2, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_revoke_admin_verification', 'لابردنی پشتڕاستکردنەوە', 'admin_accounts', 'هەژماری بەڕێوەبەر', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_view_admin_status', 'بینینی دۆخی بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 1, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_add_admin_internal_note', 'زیادکردنی تێبینی ناوخۆ بۆ بەڕێوەبەر', 'admin_accounts', 'هەژماری بەڕێوەبەر', 2, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_create_market', 'دروستکردنی مارکێت', 'market_identity', 'ناسنامەی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_view_market_profile', 'بینینی پڕۆفایلی مارکێت', 'market_identity', 'ناسنامەی مارکێت', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_edit_market_name', 'گۆڕینی ناوی مارکێت', 'market_identity', 'ناسنامەی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_edit_market_code', 'گۆڕینی کۆدی مارکێت', 'market_identity', 'ناسنامەی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_edit_market_phone', 'گۆڕینی ژمارەی مارکێت', 'market_identity', 'ناسنامەی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_edit_market_address', 'گۆڕینی ناونیشانی مارکێت', 'market_identity', 'ناسنامەی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_edit_market_region', 'گۆڕینی ناوچەی مارکێت', 'market_identity', 'ناسنامەی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_edit_market_timezone', 'گۆڕینی timezone ـی مارکێت', 'market_identity', 'ناسنامەی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_edit_market_currency', 'گۆڕینی دراوی بنەڕەتی مارکێت', 'market_identity', 'ناسنامەی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_change_primary_admin', 'گۆڕینی بەڕێوەبەری سەرەکی', 'market_identity', 'ناسنامەی مارکێت', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_add_secondary_admin', 'زیادکردنی بەڕێوەبەری دووەم', 'market_identity', 'ناسنامەی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_remove_secondary_admin', 'لابردنی بەڕێوەبەری دووەم', 'market_identity', 'ناسنامەی مارکێت', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_transfer_market', 'گواستنەوەی خاوەندارێتی مارکێت', 'market_identity', 'ناسنامەی مارکێت', 4, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true, requiresTypedConfirmation: true, requiresTwoPersonApproval: true),
  OwnerPermissionDefinition('owner_merge_market', 'یەکخستنی دوو هەژماری مارکێت', 'market_identity', 'ناسنامەی مارکێت', 4, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true, requiresTypedConfirmation: true, requiresTwoPersonApproval: true),
  OwnerPermissionDefinition('owner_split_market', 'جیاکردنەوەی هەژماری مارکێت', 'market_identity', 'ناسنامەی مارکێت', 4, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true, requiresTypedConfirmation: true, requiresTwoPersonApproval: true),
  OwnerPermissionDefinition('owner_set_market_metadata', 'گۆڕینی metadata ـی مارکێت', 'market_identity', 'ناسنامەی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_market_tags', 'دانانی tag بۆ مارکێت', 'market_identity', 'ناسنامەی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_market_priority', 'دانانی ئاستی پێشەنگی مارکێت', 'market_identity', 'ناسنامەی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_market_trial', 'خستنە دۆخی تاقیکردنەوە', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_activate_market', 'چالاککردنی مارکێت', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_market_grace', 'دانانی ماوەی Grace', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_suspend_market', 'ڕاگرتنی مارکێت', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_resume_market', 'دەستپێکردنەوەی مارکێت', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_archive_market', 'ئەرشیڤکردنی مارکێت', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_restore_market', 'گەڕاندنەوەی مارکێت', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_close_market', 'داخستنی مارکێت', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_delete_market', 'سڕینەوەی کۆتایی مارکێت', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 4, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true, requiresTypedConfirmation: true, requiresTwoPersonApproval: true),
  OwnerPermissionDefinition('owner_enable_market_read_only', 'خستنە دۆخی تەنها-خوێندنەوە', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_disable_market_read_only', 'لابردنی دۆخی تەنها-خوێندنەوە', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_enable_market_maintenance', 'چالاککردنی maintenance بۆ مارکێت', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_disable_market_maintenance', 'ناچالاککردنی maintenance', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_emergency_freeze_market', 'قوفڵکردنی فریاکەوتنی مارکێت', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 4, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true, requiresTypedConfirmation: true, requiresTwoPersonApproval: true),
  OwnerPermissionDefinition('owner_emergency_unfreeze_market', 'کردنەوەی قوفڵی فریاکەوتن', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_schedule_market_shutdown', 'خشتەکردنی داخستنی مارکێت', 'market_lifecycle', 'دۆخی ژیانی مارکێت', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_view_subscription', 'بینینی بەشداری', 'subscription', 'بەشداری و پارەدان', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_create_subscription', 'دروستکردنی بەشداری', 'subscription', 'بەشداری و پارەدان', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_change_subscription_plan', 'گۆڕینی پلانی بەشداری', 'subscription', 'بەشداری و پارەدان', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_renew_subscription', 'نوێکردنەوەی بەشداری', 'subscription', 'بەشداری و پارەدان', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_extend_subscription_days', 'زیادکردنی ڕۆژی بەشداری', 'subscription', 'بەشداری و پارەدان', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_reduce_subscription_days', 'کەمکردنەوەی ڕۆژی بەشداری', 'subscription', 'بەشداری و پارەدان', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_pause_subscription', 'وەستاندنی بەشداری', 'subscription', 'بەشداری و پارەدان', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_resume_subscription', 'دەستپێکردنەوەی بەشداری', 'subscription', 'بەشداری و پارەدان', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_cancel_subscription', 'هەڵوەشاندنەوەی بەشداری', 'subscription', 'بەشداری و پارەدان', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_set_custom_expiry', 'دانانی بەرواری کۆتایی تایبەت', 'subscription', 'بەشداری و پارەدان', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_grant_trial', 'پێدانی trial', 'subscription', 'بەشداری و پارەدان', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_grant_free_period', 'پێدانی ماوەی بەخۆڕایی', 'subscription', 'بەشداری و پارەدان', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_override_plan_price', 'گۆڕینی نرخی پلان بۆ مارکێت', 'subscription', 'بەشداری و پارەدان', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_apply_subscription_discount', 'دانانی داشکاندن', 'subscription', 'بەشداری و پارەدان', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_remove_subscription_discount', 'لابردنی داشکاندن', 'subscription', 'بەشداری و پارەدان', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_enable_auto_renew', 'چالاککردنی نوێکردنەوەی خۆکار', 'subscription', 'بەشداری و پارەدان', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_disable_auto_renew', 'ناچالاککردنی نوێکردنەوەی خۆکار', 'subscription', 'بەشداری و پارەدان', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_view_billing_history', 'بینینی مێژووی پارەدان', 'subscription', 'بەشداری و پارەدان', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_view_subscription_history', 'بینینی مێژووی بەشداری', 'subscription', 'بەشداری و پارەدان', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_correct_subscription_error', 'چاککردنەوەی هەڵەی بەشداری', 'subscription', 'بەشداری و پارەدان', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_set_employee_limit', 'دانانی سنووری کارمەند', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_device_limit', 'دانانی سنووری ئامێر', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_customer_limit', 'دانانی سنووری کڕیار', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_storage_limit', 'دانانی سنووری storage', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_attachment_limit', 'دانانی سنووری هاوپێچ', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_backup_limit', 'دانانی سنووری backup', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_backup_retention', 'دانانی ماوەی هەڵگرتنی backup', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_export_limit', 'دانانی سنووری export', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_notification_limit', 'دانانی سنووری notification', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_sms_limit', 'دانانی سنووری SMS', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_api_request_limit', 'دانانی سنووری API', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_webhook_limit', 'دانانی سنووری webhook', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_active_session_limit', 'دانانی سنووری session', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_receipt_limit', 'دانانی سنووری پسوولە', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_sync_job_limit', 'دانانی سنووری sync job', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_file_upload_limit', 'دانانی سنووری upload', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_audit_retention', 'دانانی ماوەی audit', 'resource_limits', 'سنوورەکانی سەرچاوە', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_reset_market_limits', 'گەڕاندنەوەی سنوورەکان بۆ بنەڕەت', 'resource_limits', 'سنوورەکانی سەرچاوە', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_view_feature_catalog', 'بینینی کاتەلۆگی تایبەتمەندی', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_enable_market_feature', 'چالاککردنی تایبەتمەندی بۆ مارکێت', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_disable_market_feature', 'ناچالاککردنی تایبەتمەندی بۆ مارکێت', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_inherit_market_feature', 'شوێنکەوتنی تایبەتمەندی لە پلان', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_override_market_feature', 'override ـی تایبەتمەندی مارکێت', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_clear_feature_override', 'لابردنی override', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_edit_standard_plan_features', 'گۆڕینی تایبەتمەندی پلانی Standard', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_edit_pro_plan_features', 'گۆڕینی تایبەتمەندی پلانی Pro', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_edit_vip_plan_features', 'گۆڕینی تایبەتمەندی پلانی VIP', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_create_feature', 'دروستکردنی تایبەتمەندی', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_deprecate_feature', 'کۆنکردنەوەی تایبەتمەندی', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_enable_feature_globally', 'چالاککردنی تایبەتمەندی بۆ هەمووان', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_disable_feature_globally', 'ناچالاککردنی تایبەتمەندی بۆ هەمووان', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 4, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true, requiresTypedConfirmation: true, requiresTwoPersonApproval: true),
  OwnerPermissionDefinition('owner_set_feature_rollout', 'دانانی rollout ـی تایبەتمەندی', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_view_feature_history', 'بینینی مێژووی تایبەتمەندی', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_market_feature_plan', 'دانانی پلانی تایبەتمەندی مارکێت', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_copy_feature_profile', 'کۆپیکردنی پڕۆفایلی تایبەتمەندی', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_reset_feature_profile', 'گەڕاندنەوەی پڕۆفایلی تایبەتمەندی', 'feature_entitlements', 'دەسەڵاتی تایبەتمەندی', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_view_security_dashboard', 'بینینی داشبۆردی ئاسایش', 'security', 'ئاسایش', 1, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_view_active_sessions', 'بینینی session ـە چالاکەکان', 'security', 'ئاسایش', 1, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_revoke_session', 'هەڵوەشاندنەوەی session', 'security', 'ئاسایش', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_revoke_all_sessions', 'هەڵوەشاندنەوەی هەموو session ـەکان', 'security', 'ئاسایش', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_view_devices', 'بینینی ئامێرەکان', 'security', 'ئاسایش', 1, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_block_device', 'بلۆککردنی ئامێر', 'security', 'ئاسایش', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_unblock_device', 'لابردنی بلۆکی ئامێر', 'security', 'ئاسایش', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_require_password_reset', 'ناچارکردنی reset ـی وشەی نهێنی', 'security', 'ئاسایش', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_require_2fa', 'ناچارکردنی 2FA', 'security', 'ئاسایش', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_disable_2fa', 'ناچالاککردنی 2FA', 'security', 'ئاسایش', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_set_session_timeout', 'دانانی session timeout', 'security', 'ئاسایش', 2, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_login_attempt_limit', 'دانانی سنووری هەوڵی login', 'security', 'ئاسایش', 2, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_lock_suspicious_account', 'قوفڵکردنی هەژماری گومانلێکراو', 'security', 'ئاسایش', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_unlock_suspicious_account', 'کردنەوەی قوفڵی هەژماری گومانلێکراو', 'security', 'ئاسایش', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_view_security_incidents', 'بینینی ڕووداوە ئاسایشییەکان', 'security', 'ئاسایش', 1, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_resolve_security_incident', 'چارەسەرکردنی ڕووداوی ئاسایشی', 'security', 'ئاسایش', 2, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_rotate_market_api_key', 'گۆڕینی API key ـی مارکێت', 'security', 'ئاسایش', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_revoke_market_api_key', 'هەڵوەشاندنەوەی API key', 'security', 'ئاسایش', 3, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_rotate_market_secret', 'گۆڕینی secret ـی مارکێت', 'security', 'ئاسایش', 4, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true, requiresTypedConfirmation: true, requiresTwoPersonApproval: true),
  OwnerPermissionDefinition('owner_view_security_history', 'بینینی مێژووی ئاسایش', 'security', 'ئاسایش', 1, <OwnerPermissionScope>{OwnerPermissionScope.admin, OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_support_standard', 'دانانی پشتیوانی Standard', 'support', 'پشتیوانی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_support_priority', 'دانانی پشتیوانی Priority', 'support', 'پشتیوانی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_support_vip', 'دانانی پشتیوانی VIP', 'support', 'پشتیوانی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_assign_support_agent', 'دیاریکردنی ئەجێنتی پشتیوانی', 'support', 'پشتیوانی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_add_internal_support_note', 'زیادکردنی تێبینی پشتیوانی', 'support', 'پشتیوانی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_view_support_history', 'بینینی مێژووی پشتیوانی', 'support', 'پشتیوانی', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_mark_market_high_priority', 'خستنە پێشەنگی بەرز', 'support', 'پشتیوانی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_set_support_sla', 'دانانی SLA', 'support', 'پشتیوانی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_open_support_case', 'کردنەوەی کەیسی پشتیوانی', 'support', 'پشتیوانی', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_close_support_case', 'داخستنی کەیسی پشتیوانی', 'support', 'پشتیوانی', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_view_backup_health', 'بینینی تەندروستی backup', 'backup_recovery', 'Backup و Recovery', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_market_backups', 'بینینی backup ـەکانی مارکێت', 'backup_recovery', 'Backup و Recovery', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_trigger_market_backup', 'دەستپێکردنی backup ـی مارکێت', 'backup_recovery', 'Backup و Recovery', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_trigger_platform_backup', 'دەستپێکردنی backup ـی پلاتفۆرم', 'backup_recovery', 'Backup و Recovery', 3, <OwnerPermissionScope>{OwnerPermissionScope.platform}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_download_backup', 'داگرتنی backup', 'backup_recovery', 'Backup و Recovery', 2, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_verify_backup', 'پشتڕاستکردنەوەی backup', 'backup_recovery', 'Backup و Recovery', 2, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_restore_market_backup', 'restore ـی backup ـی مارکێت', 'backup_recovery', 'Backup و Recovery', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_restore_platform_backup', 'restore ـی backup ـی پلاتفۆرم', 'backup_recovery', 'Backup و Recovery', 4, <OwnerPermissionScope>{OwnerPermissionScope.platform}, requiresReason: true, requiresReauth: true, requiresTypedConfirmation: true, requiresTwoPersonApproval: true),
  OwnerPermissionDefinition('owner_delete_backup', 'سڕینەوەی backup', 'backup_recovery', 'Backup و Recovery', 3, <OwnerPermissionScope>{OwnerPermissionScope.platform}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_change_backup_retention', 'گۆڕینی ماوەی هەڵگرتنی backup', 'backup_recovery', 'Backup و Recovery', 2, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_start_disaster_recovery', 'دەستپێکردنی disaster recovery', 'backup_recovery', 'Backup و Recovery', 4, <OwnerPermissionScope>{OwnerPermissionScope.platform}, requiresReason: true, requiresReauth: true, requiresTypedConfirmation: true, requiresTwoPersonApproval: true),
  OwnerPermissionDefinition('owner_stop_disaster_recovery', 'وەستاندنی disaster recovery', 'backup_recovery', 'Backup و Recovery', 3, <OwnerPermissionScope>{OwnerPermissionScope.platform}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_view_sync_health', 'بینینی تەندروستی sync', 'sync_integration', 'Sync و Integration', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_view_sync_failures', 'بینینی sync ـە شکستخواردووەکان', 'sync_integration', 'Sync و Integration', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_pause_sync', 'وەستاندنی sync', 'sync_integration', 'Sync و Integration', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_resume_sync', 'دەستپێکردنەوەی sync', 'sync_integration', 'Sync و Integration', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_retry_sync', 'دووبارەکردنەوەی sync', 'sync_integration', 'Sync و Integration', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_clear_failed_sync_queue', 'پاککردنەوەی ڕیزی sync ـی شکستخواردوو', 'sync_integration', 'Sync و Integration', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_view_integrations', 'بینینی integration ـەکان', 'sync_integration', 'Sync و Integration', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_enable_integration', 'چالاککردنی integration', 'sync_integration', 'Sync و Integration', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_disable_integration', 'ناچالاککردنی integration', 'sync_integration', 'Sync و Integration', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_view_webhooks', 'بینینی webhook ـەکان', 'sync_integration', 'Sync و Integration', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_retry_webhook', 'دووبارەکردنەوەی webhook', 'sync_integration', 'Sync و Integration', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_disable_webhook', 'ناچالاککردنی webhook', 'sync_integration', 'Sync و Integration', 3, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_rotate_integration_secret', 'گۆڕینی secret ـی integration', 'sync_integration', 'Sync و Integration', 4, <OwnerPermissionScope>{OwnerPermissionScope.market}, requiresReason: true, requiresReauth: true, requiresTypedConfirmation: true, requiresTwoPersonApproval: true),
  OwnerPermissionDefinition('owner_test_integration', 'تاقیکردنەوەی integration', 'sync_integration', 'Sync و Integration', 2, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_view_app_versions', 'بینینی وەشانەکانی ئەپ', 'app_version', 'وەشان و Update', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_set_minimum_app_version', 'دانانی کەمترین وەشانی ڕێگەپێدراو', 'app_version', 'وەشان و Update', 2, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_force_app_update', 'ناچارکردنی app update', 'app_version', 'وەشان و Update', 4, <OwnerPermissionScope>{OwnerPermissionScope.platform}, requiresReason: true, requiresReauth: true, requiresTypedConfirmation: true, requiresTwoPersonApproval: true),
  OwnerPermissionDefinition('owner_disable_forced_update', 'لابردنی forced update', 'app_version', 'وەشان و Update', 3, <OwnerPermissionScope>{OwnerPermissionScope.platform}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_block_old_app_version', 'بلۆککردنی وەشانی کۆن', 'app_version', 'وەشان و Update', 3, <OwnerPermissionScope>{OwnerPermissionScope.platform}, requiresReason: true, requiresReauth: true),
  OwnerPermissionDefinition('owner_allow_old_app_version', 'ڕێگەدان بە وەشانی کۆن', 'app_version', 'وەشان و Update', 2, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_publish_update_message', 'بڵاوکردنەوەی پەیامی update', 'app_version', 'وەشان و Update', 2, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_set_update_deadline', 'دانانی دواوادەی update', 'app_version', 'وەشان و Update', 2, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_backend_health', 'بینینی تەندروستی backend', 'platform_health', 'تەندروستی پلاتفۆرم', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_database_health', 'بینینی تەندروستی database', 'platform_health', 'تەندروستی پلاتفۆرم', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_edge_function_health', 'بینینی تەندروستی Edge Functions', 'platform_health', 'تەندروستی پلاتفۆرم', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_storage_health', 'بینینی تەندروستی storage', 'platform_health', 'تەندروستی پلاتفۆرم', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_queue_health', 'بینینی تەندروستی queue', 'platform_health', 'تەندروستی پلاتفۆرم', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_platform_error_rate', 'بینینی ڕێژەی هەڵە', 'platform_health', 'تەندروستی پلاتفۆرم', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_platform_latency', 'بینینی latency ـی پلاتفۆرم', 'platform_health', 'تەندروستی پلاتفۆرم', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_refresh_platform_config', 'نوێکردنەوەی configuration', 'platform_health', 'تەندروستی پلاتفۆرم', 2, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_owner_audit', 'بینینی audit ـی Owner', 'audit', 'Audit و بەدواداچوون', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_export_owner_audit', 'هەناردەکردنی audit ـی Owner', 'audit', 'Audit و بەدواداچوون', 2, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_admin_audit', 'بینینی audit ـی بەڕێوەبەر', 'audit', 'Audit و بەدواداچوون', 1, <OwnerPermissionScope>{OwnerPermissionScope.admin}),
  OwnerPermissionDefinition('owner_view_market_audit', 'بینینی audit ـی مارکێت', 'audit', 'Audit و بەدواداچوون', 1, <OwnerPermissionScope>{OwnerPermissionScope.market}),
  OwnerPermissionDefinition('owner_view_before_after_state', 'بینینی before/after state', 'audit', 'Audit و بەدواداچوون', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
  OwnerPermissionDefinition('owner_view_rollback_history', 'بینینی مێژووی rollback', 'audit', 'Audit و بەدواداچوون', 1, <OwnerPermissionScope>{OwnerPermissionScope.platform}),
];

const ownerPermissionCount = 200;

OwnerPermissionDefinition? ownerPermissionByKey(String key) {
  for (final permission in ownerPermissionDefinitions) {
    if (permission.key == key) return permission;
  }
  return null;
}

bool isKnownOwnerPermission(String key) => ownerPermissionByKey(key) != null;
