from pathlib import Path
import os

ROOT = Path(os.environ.get('REPO_ROOT', Path.cwd())).resolve()


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected exactly one match, found {count}')
    return text.replace(old, new, 1)


# 1) Canonical finance helpers: debt/payment amount + remaining are stored in base IQD.
helpers_path = ROOT / 'lib/utils/helpers.dart'
helpers = helpers_path.read_text(encoding='utf-8')
old_helpers = '''  /// Normalize one debt field to IQD using the rate stored on that debt.\n  /// A USD debt without a valid historical rate is unknown, never silently mixed.\n  static double? debtValueInIqd(RecordModel debt, String field) {\n    final value = debt.getDoubleValue(field);\n    final rawCurrency = debt.getStringValue('currency').trim();\n    final currency = rawCurrency.isEmpty ? 'IQD' : rawCurrency.toUpperCase();\n    if (currency != 'USD') return value;\n    final rate = debt.getDoubleValue('dollar_rate');\n    if (rate <= 0) return null;\n    return value * rate;\n  }\n\n  static ({\n    double totalDebt,\n    double totalRemaining,\n    double totalPaid,\n    bool complete,\n  }) debtSummaryInIqd(Iterable<RecordModel> debts) {\n    var totalDebt = 0.0;\n    var totalRemaining = 0.0;\n    var complete = true;\n    for (final debt in debts) {\n      final amount = debtValueInIqd(debt, 'amount');\n      final remaining = debtValueInIqd(debt, 'remaining');\n      if (amount == null || remaining == null) {\n        complete = false;\n        continue;\n      }\n      totalDebt += amount;\n      totalRemaining += remaining;\n    }\n    var totalPaid = totalDebt - totalRemaining;\n    if (totalPaid.abs() < 0.000001) totalPaid = 0;\n    return (\n      totalDebt: totalDebt,\n      totalRemaining: totalRemaining,\n      totalPaid: totalPaid,\n      complete: complete,\n    );\n  }\n'''
new_helpers = '''  /// Canonical finance storage is IQD. `currency` and `dollar_rate` are display\n  /// metadata for legacy USD-tagged debts; amount/remaining/payment.amount stay\n  /// in the same base IQD unit used by record_payment.\n  static double debtValueInIqd(RecordModel debt, String field) {\n    return debt.getDoubleValue(field);\n  }\n\n  /// Convert a canonical IQD storage amount into the debt's display currency.\n  /// A USD label without a valid historical rate cannot be converted safely.\n  static double? storageAmountToDisplay(\n    double storageAmount,\n    String currency, {\n    double dollarRate = 0,\n  }) {\n    final normalized = currency.trim().toUpperCase();\n    if (normalized != 'USD') return storageAmount;\n    if (dollarRate <= 0) return null;\n    return storageAmount / dollarRate;\n  }\n\n  /// Format a canonical IQD storage amount without ever presenting IQD as USD.\n  /// If USD conversion metadata is incomplete, fail safe to the known IQD value.\n  static String formatStoredFinancialAmount(\n    double storageAmount,\n    String currency, {\n    double dollarRate = 0,\n    bool showConversion = true,\n  }) {\n    final normalized = currency.trim().toUpperCase();\n    final display = storageAmountToDisplay(\n      storageAmount,\n      normalized,\n      dollarRate: dollarRate,\n    );\n    if (normalized == 'USD' && display != null) {\n      return formatCurrencyWithType(\n        display,\n        'USD',\n        dollarRate: dollarRate,\n        showConversion: showConversion,\n      );\n    }\n    return formatCurrency(storageAmount);\n  }\n\n  static ({\n    double totalDebt,\n    double totalRemaining,\n    double totalPaid,\n    bool complete,\n  }) debtSummaryInIqd(Iterable<RecordModel> debts) {\n    var totalDebt = 0.0;\n    var totalRemaining = 0.0;\n    var complete = true;\n    for (final debt in debts) {\n      final amount = debtValueInIqd(debt, 'amount');\n      final remaining = debtValueInIqd(debt, 'remaining');\n      if (!amount.isFinite || !remaining.isFinite) {\n        complete = false;\n        continue;\n      }\n      totalDebt += amount;\n      totalRemaining += remaining;\n    }\n    var totalPaid = totalDebt - totalRemaining;\n    if (totalPaid.abs() < 0.000001) totalPaid = 0;\n    return (\n      totalDebt: totalDebt,\n      totalRemaining: totalRemaining,\n      totalPaid: totalPaid,\n      complete: complete,\n    );\n  }\n'''
helpers = replace_once(helpers, old_helpers, new_helpers, 'helpers canonical finance block')
helpers_path.write_text(helpers, encoding='utf-8')

# 2) Financial Chat: ledger math uses storage IQD; USD is display-only.
profile_path = ROOT / 'lib/screens/shared/user_profile_screen.dart'
profile = profile_path.read_text(encoding='utf-8')
profile = replace_once(profile, '''  double? _timelineAmountInIqd(_ProfileTimelineItem item) {\n    if (item.isSystem) return 0;\n    final amount = item.record.getDoubleValue('amount');\n    final debt = item.isPayment ? item.relatedDebt : item.record;\n    if (debt == null) return null;\n    final currency = debt.getStringValue('currency').isEmpty\n        ? 'IQD'\n        : debt.getStringValue('currency');\n    if (currency != 'USD') return amount;\n    final rate = debt.getDoubleValue('dollar_rate');\n    if (rate <= 0) return null;\n    return amount * rate;\n  }\n''', '''  double? _timelineAmountInIqd(_ProfileTimelineItem item) {\n    if (item.isSystem) return 0;\n    // Debt and payment amounts share one canonical base IQD storage unit.\n    return item.record.getDoubleValue('amount');\n  }\n''', 'timeline IQD normalization')

profile = replace_once(profile, '''    final amountText = amount > 0\n        ? AppHelpers.formatCurrencyWithType(amount, currency)\n        : '';\n''', '''    // Audit events store the canonical amount but do not snapshot dollar_rate.\n    // Never relabel that known IQD value as USD without a safe conversion rate.\n    final amountText = amount > 0 ? AppHelpers.formatCurrency(amount) : '';\n''', 'system event amount formatting')

profile = replace_once(profile, '''    final formattedAmount = AppHelpers.formatCurrencyWithType(\n      amount,\n      currency,\n      dollarRate: dollarRate,\n      showConversion: currency == 'USD',\n    );\n''', '''    final formattedAmount = AppHelpers.formatStoredFinancialAmount(\n      amount,\n      currency,\n      dollarRate: dollarRate,\n      showConversion: currency == 'USD',\n    );\n''', 'timeline bubble amount formatting')

profile = replace_once(profile, '''    final amountText = AppHelpers.formatCurrencyWithType(\n      amount,\n      currency,\n      dollarRate: debt.getDoubleValue('dollar_rate'),\n      showConversion: currency == 'USD',\n    );\n''', '''    final amountText = AppHelpers.formatStoredFinancialAmount(\n      amount,\n      currency,\n      dollarRate: debt.getDoubleValue('dollar_rate'),\n      showConversion: currency == 'USD',\n    );\n''', 'payment debt reference formatting')

profile = replace_once(profile, '''    final text = (isPayment\n            ? record.getStringValue('note')\n            : record.getStringValue('description'))\n        .trim();\n    final amountText = AppHelpers.formatCurrencyWithType(amount, currency);\n''', '''    final text = (isPayment\n            ? record.getStringValue('note')\n            : record.getStringValue('description'))\n        .trim();\n    final dollarRate = isPayment\n        ? (item.relatedDebt?.getDoubleValue('dollar_rate') ?? 0)\n        : record.getDoubleValue('dollar_rate');\n    final amountText = AppHelpers.formatStoredFinancialAmount(\n      amount,\n      currency,\n      dollarRate: dollarRate,\n      showConversion: currency == 'USD',\n    );\n''', 'reply label formatting')

profile = replace_once(profile, '''    final text = snapshot['text']?.toString().trim() ?? '';\n    final label = kind == 'payment' ? 'وەڵام بۆ پارەدانەوە' : 'وەڵام بۆ قەرز';\n    final amountText = AppHelpers.formatCurrencyWithType(amount, currency);\n''', '''    final text = snapshot['text']?.toString().trim() ?? '';\n    final dollarRate =\n        double.tryParse('${snapshot['dollar_rate'] ?? 0}') ?? 0;\n    final label = kind == 'payment' ? 'وەڵام بۆ پارەدانەوە' : 'وەڵام بۆ قەرز';\n    final amountText = AppHelpers.formatStoredFinancialAmount(\n      amount,\n      currency,\n      dollarRate: dollarRate,\n      showConversion: currency == 'USD',\n    );\n''', 'persistent reference formatting')

profile = replace_once(profile, '''        final currency = debt?.getStringValue('currency').isNotEmpty == true\n            ? debt!.getStringValue('currency')\n            : 'IQD';\n        return Container(\n''', '''        final currency = debt?.getStringValue('currency').isNotEmpty == true\n            ? debt!.getStringValue('currency')\n            : 'IQD';\n        final dollarRate = debt?.getDoubleValue('dollar_rate') ?? 0;\n        return Container(\n''', 'transaction action rate')

profile = replace_once(profile, '''                subtitle: Text(\n                  AppHelpers.formatCurrencyWithType(amount, currency),\n                  textDirection: TextDirection.ltr,\n                ),\n''', '''                subtitle: Text(\n                  AppHelpers.formatStoredFinancialAmount(\n                    amount,\n                    currency,\n                    dollarRate: dollarRate,\n                    showConversion: currency == 'USD',\n                  ),\n                  textDirection: TextDirection.ltr,\n                ),\n''', 'transaction action amount')

profile = replace_once(profile, '''                    AppHelpers.formatCurrencyWithType(\n                      debt.getDoubleValue('remaining'),\n                      currency,\n                    ),\n''', '''                    AppHelpers.formatStoredFinancialAmount(\n                      debt.getDoubleValue('remaining'),\n                      currency,\n                      dollarRate: dollarRate,\n                      showConversion: currency == 'USD',\n                    ),\n''', 'full pay remaining formatting')
profile_path.write_text(profile, encoding='utf-8')

# 3) Financial Chat PDF: incoming values are canonical IQD storage amounts.
pdf_path = ROOT / 'lib/services/pdf_service.dart'
pdf = pdf_path.read_text(encoding='utf-8')
pdf = replace_once(pdf, '''    String money(double value, String currency, double rate) {\n      if (currency == 'USD') {\n        final usd = NumberFormat('#,##0.00', 'en').format(value);\n        if (rate > 0) {\n          return '\\$$usd (${formatter.format(value * rate)} د.ع)';\n        }\n        return '\\$$usd';\n      }\n      return '${formatter.format(value)} د.ع';\n    }\n''', '''    String money(double storageValue, String currency, double rate) {\n      final normalized = currency.trim().toUpperCase();\n      if (normalized == 'USD' && rate > 0) {\n        final displayUsd = storageValue / rate;\n        final usd = NumberFormat('#,##0.00', 'en').format(displayUsd);\n        return '\\$$usd (${formatter.format(storageValue)} د.ع)';\n      }\n      // Without a historical rate the only trustworthy value is storage IQD.\n      return '${formatter.format(storageValue)} د.ع';\n    }\n''', 'financial chat PDF money')
pdf_path.write_text(pdf, encoding='utf-8')

# 4) Regression tests lock canonical storage + display conversion behavior.
test_path = ROOT / 'test/widget_test.dart'
test = test_path.read_text(encoding='utf-8')
old_tests = '''    test('normalizes mixed IQD and USD using the historical debt rate', () {\n      final summary = AppHelpers.debtSummaryInIqd([\n        debt(id: 'iqd', amount: 100000, remaining: 60000, currency: 'IQD'),\n        debt(id: 'usd', amount: 50, remaining: 20, currency: 'USD', rate: 1500),\n      ]);\n      expect(summary.complete, isTrue);\n      expect(summary.totalDebt, 175000);\n      expect(summary.totalRemaining, 90000);\n      expect(summary.totalPaid, 85000);\n    });\n\n    test('fails closed when a USD debt has no valid historical rate', () {\n      final summary = AppHelpers.debtSummaryInIqd([\n        debt(id: 'usd-no-rate', amount: 50, remaining: 20, currency: 'USD'),\n      ]);\n      expect(summary.complete, isFalse);\n    });\n'''
new_tests = '''    test('sums canonical IQD storage even for a legacy USD display tag', () {\n      final summary = AppHelpers.debtSummaryInIqd([\n        debt(id: 'iqd', amount: 100000, remaining: 60000, currency: 'IQD'),\n        debt(\n          id: 'legacy-usd',\n          amount: 75000,\n          remaining: 30000,\n          currency: 'USD',\n          rate: 1500,\n        ),\n      ]);\n      expect(summary.complete, isTrue);\n      expect(summary.totalDebt, 175000);\n      expect(summary.totalRemaining, 90000);\n      expect(summary.totalPaid, 85000);\n    });\n\n    test('converts storage IQD to USD only for display', () {\n      expect(\n        AppHelpers.storageAmountToDisplay(75000, 'USD', dollarRate: 1500),\n        50,\n      );\n      expect(\n        AppHelpers.formatStoredFinancialAmount(\n          75000,\n          'USD',\n          dollarRate: 1500,\n        ),\n        r'$50.00 (75,000 د.ع)',\n      );\n    });\n\n    test('falls back to known IQD when USD display rate is missing', () {\n      final summary = AppHelpers.debtSummaryInIqd([\n        debt(\n          id: 'legacy-usd-no-rate',\n          amount: 75000,\n          remaining: 30000,\n          currency: 'USD',\n        ),\n      ]);\n      expect(summary.complete, isTrue);\n      expect(summary.totalDebt, 75000);\n      expect(\n        AppHelpers.formatStoredFinancialAmount(75000, 'USD'),\n        '75,000 د.ع',\n      );\n    });\n'''
test = replace_once(test, old_tests, new_tests, 'currency regression tests')
test_path.write_text(test, encoding='utf-8')

# 5) CI policy markers: protect the canonical storage contract.
verifier_path = ROOT / 'scripts/verify_online_only.py'
verifier = verifier_path.read_text(encoding='utf-8')
verifier = replace_once(verifier, '''# Currency-safe financial totals: never add raw USD values into IQD summaries.\nhelpers_source = (LIB / 'utils/helpers.dart').read_text(encoding='utf-8')\n''', '''# Currency-safe financial totals: canonical amount/remaining/payment values are\n# stored in IQD; USD is display metadata and must never be multiplied twice.\nhelpers_source = (LIB / 'utils/helpers.dart').read_text(encoding='utf-8')\n''', 'verifier currency comment')
verifier = replace_once(verifier, '''for marker in ('debtValueInIqd', 'debtSummaryInIqd'):\n''', '''for marker in (\n    'debtValueInIqd',\n    'storageAmountToDisplay',\n    'formatStoredFinancialAmount',\n    'debtSummaryInIqd',\n):\n''', 'verifier helper markers')
verifier = replace_once(verifier, '''for marker in ('AppHelpers.debtSummaryInIqd(_debts)', '_buildCurrencySummaryWarning', '_showIncompleteCurrencySummaryMessage'):\n''', '''for marker in (\n    'AppHelpers.debtSummaryInIqd(_debts)',\n    'AppHelpers.formatStoredFinancialAmount',\n    '_buildCurrencySummaryWarning',\n    '_showIncompleteCurrencySummaryMessage',\n):\n''', 'verifier profile markers')
verifier_path.write_text(verifier, encoding='utf-8')

print('Canonical IQD storage/display fix applied.')
