import { createClient } from "npm:@supabase/supabase-js@2.116.0";

function envJsonKey(name:string):string|null{const raw=Deno.env.get(name);if(!raw)return null;try{const p=JSON.parse(raw) as Record<string,string>;return p.default??Object.values(p)[0]??null}catch(_){return raw}}
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
async function eq(a:string,b:string){const e=new TextEncoder();const[ah,bh]=await Promise.all([crypto.subtle.digest("SHA-256",e.encode(a)),crypto.subtle.digest("SHA-256",e.encode(b))]);const x=new Uint8Array(ah),y=new Uint8Array(bh);let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0}
function n(v:unknown){const x=Number(v??0);return Number.isFinite(x)?Math.trunc(x):0}
function buildDigest(data:any, localDate:string){const o=data?.overview??{};const items=Array.isArray(data?.items)?data.items:[];const flagged=items.filter((x:any)=>String(x?.health?.status??'')!=='healthy').slice(0,5);const lines=[`📊 ZHIROX • Daily Owner Digest`,`📅 ${localDate}`,``,`🏪 مارکێت: ${n(o.total_markets)} • Healthy: ${n(o.healthy)} • Degraded: ${n(o.degraded)} • Attention: ${n(o.attention)}`,`⚙️ Queue: ${n(o.active_queue)} • Retry: ${n(o.retrying)} • Dead-letter: ${n(o.dead_letter)}`,`🤖 AutoPilot: ${n(o.autopilot_enabled)} ON • ${n(o.autopilot_disabled)} OFF`,`📨 Telegram linked: ${n(o.telegram_linked_customers)}`,`🛡️ Risk: ${n(o.risk_total)} • High: ${n(o.risk_high)} • Critical: ${n(o.risk_critical)}`];if(flagged.length){lines.push(``,`⚠️ پێویستی بە سەرنج:`);for(const m of flagged){const h=m?.health??{};lines.push(`• ${String(m?.market_name??'مارکێت')} — ${String(h?.status??'attention')} • Queue ${n(h.active_queue)} • Dead ${n(h.dead_letter)}`)}}else{lines.push(``,`✅ هیچ مارکێتێکی کێشەدار نییە.`)}lines.push(``,`🕒 کورتەی خۆکار • 08:30 Asia/Baghdad`);return lines.join("\n")}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return json({error:"method_not_allowed"},405);const url=(Deno.env.get("SUPABASE_URL")??"").trim();const secret=(Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??envJsonKey("SUPABASE_SECRET_KEYS")??"").trim();if(!url||!secret)return json({error:"server_not_configured"},500);const admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});
 const rt=await admin.rpc("get_customer_push_runtime_config_service");if(rt.error)return json({error:"worker_runtime_unavailable"},500);const expected=String(rt.data?.customer_push_worker_secret??"").trim(),provided=(req.headers.get("x-zhirox-push-worker")??"").trim();if(!expected||!provided||!(await eq(expected,provided)))return json({error:"unauthorized"},401);
 const cfg=await admin.rpc("get_telegram_runtime_config_service");if(cfg.error)return json({error:"telegram_config_unavailable"},500);const cr=Array.isArray(cfg.data)?cfg.data[0]:cfg.data;const token=String(cr?.bot_token??"").trim();if(!token)return json({ok:true,processed:0,reason:"telegram_not_configured"});
 const claim=await admin.rpc("claim_owner_daily_digest_service");if(claim.error)return json({error:"claim_failed"},500);let processed=0,sent=0,failed=0;
 for(const row of claim.data??[]){processed++;const owner=String(row.owner_user_id??""),chat=String(row.chat_id??"").trim(),day=String(row.local_date??"");if(!owner||!chat||!day)continue;try{const ov=await admin.rpc("get_system_owner_autopilot_overview_service",{p_search:"",p_health:"all",p_page:1,p_per_page:100});if(ov.error)throw new Error("overview_failed");const text=buildDigest(ov.data,day);const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chat_id:chat,text,disable_web_page_preview:true}),signal:AbortSignal.timeout(8000)});let body:any={};try{body=await r.json()}catch(_){}if(!r.ok||body?.ok!==true)throw new Error(String(body?.description??`telegram_http_${r.status}`));await admin.rpc("finish_owner_daily_digest_service",{p_owner_user_id:owner,p_local_date:day,p_success:true,p_error:null});sent++}catch(error){await admin.rpc("finish_owner_daily_digest_service",{p_owner_user_id:owner,p_local_date:day,p_success:false,p_error:String(error instanceof Error?error.message:error).slice(0,500)});failed++}}
 return json({ok:true,processed,sent,failed});
});