-- Historical migration marker.
-- The complete schema effect of this migration is already defined in:
--   20260920222142_daftar_credit_limit_gateway_audit.sql
-- Keep this timestamped file so repository history remains explicit without
-- executing an identical schema migration twice on fresh installations.
