-- Existing receipt numbers remain untouched. New numbers are generated by the
-- database, independently of a market's editable receipt template snapshot.
alter table public.market_receipt_settings
  add column if not exists payment_title text not null default 'پسوولەی پارەدانەوە';

create or replace function private.assign_receipt_identity()
returns trigger language plpgsql security definer set search_path to 'pg_catalog'
as $function$
declare
  v_year integer := extract(year from current_timestamp)::integer;
  v_number bigint;
begin
  insert into private.receipt_counters (admin_id, receipt_year, next_number)
  values (new.admin_id, v_year, 2)
  on conflict (admin_id, receipt_year)
  do update set next_number = private.receipt_counters.next_number + 1
  returning next_number - 1 into v_number;

  new.receipt_number := 'INV-' || v_year::text || '-' || lpad(v_number::text, 6, '0');
  return new;
end;
$function$;

-- Recreate the trigger so installations with an older schema also use the
-- protected generator. The table already denies updates to authenticated users.
drop trigger if exists trg_receipt_documents_identity on public.receipt_documents;
create trigger trg_receipt_documents_identity
before insert on public.receipt_documents
for each row execute function private.assign_receipt_identity();
