
-- Backup runtime resilience:
-- 1) one canonical all-tenant daily backup job;
-- 2) no resurrected Daftar-only duplicate backup job;
-- 3) hourly catch-up for missing/stale tenant backups;
-- 4) per-tenant runtime event history for owner diagnostics.

create table if not exists private.backup_runtime_events (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references public.profiles(id) on delete cascade,
  run_kind text not null check (run_kind in ('daily','catchup')),
  status text not null check (status in ('success','failure','skipped_locked')),
  backup_id uuid,
  error_code text,
  error_message text,
  created_at timestamptz not null default now()
);

revoke all on table private.backup_runtime_events
  from public, anon, authenticated;
grant select, insert, update, delete on table private.backup_runtime_events
  to service_role;

create index if not exists backup_runtime_events_admin_time_idx
  on private.backup_runtime_events(admin_id, created_at desc);
create index if not exists backup_runtime_events_failure_time_idx
  on private.backup_runtime_events(created_at desc)
  where status='failure';

create or replace function private.run_all_tenant_backups()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  r record;
  v_result jsonb;
  v_ok integer := 0;
  v_errors integer := 0;
  v_locked integer := 0;
begin
  for r in
    select p.id as admin_id
    from public.profiles p
    where p.role='admin'
      and coalesce(p.is_system_owner,false)=false
    order by p.id
  loop
    if not pg_try_advisory_xact_lock(
      hashtextextended('zhirox:tenant-backup:'||r.admin_id::text,0)
    ) then
      v_locked := v_locked + 1;
      insert into private.backup_runtime_events(
        admin_id,run_kind,status,error_code,error_message
      ) values (
        r.admin_id,'daily','skipped_locked','backup_lock_busy',
        'Another backup transaction already holds the tenant backup lock.'
      );
      continue;
    end if;

    begin
      v_result := private.run_scheduled_tenant_backup(r.admin_id);
      v_ok := v_ok + 1;
      insert into private.backup_runtime_events(
        admin_id,run_kind,status,backup_id
      ) values (
        r.admin_id,'daily','success',
        nullif(v_result->>'backup_id','')::uuid
      );
    exception when others then
      v_errors := v_errors + 1;
      insert into private.backup_runtime_events(
        admin_id,run_kind,status,error_code,error_message
      ) values (
        r.admin_id,'daily','failure',sqlstate,left(sqlerrm,1000)
      );
    end;
  end loop;

  delete from private.backup_runtime_events
  where created_at < now()-interval '90 days';

  return jsonb_build_object(
    'backed_up_tenants',v_ok,
    'backup_errors',v_errors,
    'skipped_locked',v_locked,
    'scope','all_non_owner_admin_tenants'
  );
end;
$function$;

revoke execute on function private.run_all_tenant_backups()
  from public, anon, authenticated;

create or replace function private.run_backup_catchup()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  r record;
  v_result jsonb;
  v_ok integer := 0;
  v_errors integer := 0;
  v_locked integer := 0;
  v_candidates integer := 0;
begin
  for r in
    select
      a.id as admin_id,
      b.latest_backup_at
    from public.profiles a
    left join public.owner_tenant_controls c
      on c.admin_id=a.id
    left join lateral (
      select max(tb.created_at) as latest_backup_at
      from public.tenant_backups tb
      where tb.admin_id=a.id
    ) b on true
    where a.role='admin'
      and coalesce(a.is_system_owner,false)=false
      and a.active=true
      and a.approved=true
      and coalesce(c.lifecycle_status,'active') not in ('suspended','archived')
      and (
        b.latest_backup_at is null
        or b.latest_backup_at < now()-interval '26 hours'
      )
    order by a.id
  loop
    v_candidates := v_candidates + 1;

    if not pg_try_advisory_xact_lock(
      hashtextextended('zhirox:tenant-backup:'||r.admin_id::text,0)
    ) then
      v_locked := v_locked + 1;
      insert into private.backup_runtime_events(
        admin_id,run_kind,status,error_code,error_message
      ) values (
        r.admin_id,'catchup','skipped_locked','backup_lock_busy',
        'Daily or catch-up backup is already running for this tenant.'
      );
      continue;
    end if;

    begin
      v_result := private.run_scheduled_tenant_backup(r.admin_id);
      v_ok := v_ok + 1;
      insert into private.backup_runtime_events(
        admin_id,run_kind,status,backup_id
      ) values (
        r.admin_id,'catchup','success',
        nullif(v_result->>'backup_id','')::uuid
      );
    exception when others then
      v_errors := v_errors + 1;
      insert into private.backup_runtime_events(
        admin_id,run_kind,status,error_code,error_message
      ) values (
        r.admin_id,'catchup','failure',sqlstate,left(sqlerrm,1000)
      );
    end;
  end loop;

  delete from private.backup_runtime_events
  where created_at < now()-interval '90 days';

  return jsonb_build_object(
    'candidate_tenants',v_candidates,
    'catchup_success',v_ok,
    'catchup_errors',v_errors,
    'skipped_locked',v_locked,
    'stale_after_hours',26
  );
end;
$function$;

revoke execute on function private.run_backup_catchup()
  from public, anon, authenticated;

create or replace function private.guard_backup_runtime()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  j record;
  v_job_id bigint;
  v_removed_legacy integer := 0;
begin
  for j in
    select jobid
    from cron.job
    where jobname in (
      'daily-daftar-tenant-backup-all',
      'daily-tenant-backup-account-28'
    )
  loop
    perform cron.unschedule(j.jobid);
    v_removed_legacy := v_removed_legacy + 1;
  end loop;

  select jobid into v_job_id
  from cron.job
  where jobname='daily-tenant-backup-all'
  limit 1;

  if v_job_id is null then
    perform cron.schedule(
      'daily-tenant-backup-all',
      '30 2 * * *',
      'select private.run_all_tenant_backups();'
    );
  else
    perform cron.alter_job(
      job_id=>v_job_id,
      schedule=>'30 2 * * *',
      command=>'select private.run_all_tenant_backups();',
      active=>true
    );
  end if;

  select jobid into v_job_id
  from cron.job
  where jobname='backup-catchup-watchdog'
  limit 1;

  if v_job_id is null then
    perform cron.schedule(
      'backup-catchup-watchdog',
      '37 * * * *',
      'select private.run_backup_catchup();'
    );
  else
    perform cron.alter_job(
      job_id=>v_job_id,
      schedule=>'37 * * * *',
      command=>'select private.run_backup_catchup();',
      active=>true
    );
  end if;

  return jsonb_build_object(
    'legacy_jobs_removed',v_removed_legacy,
    'canonical_daily_job','daily-tenant-backup-all',
    'catchup_job','backup-catchup-watchdog'
  );
end;
$function$;

revoke execute on function private.guard_backup_runtime()
  from public, anon, authenticated;

CREATE OR REPLACE FUNCTION private.guard_daftar_sync_sources()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  r record;
  j record;
  v_secret text;
  v_valid integer := 0;
  v_invalid integer := 0;
  v_job_id bigint;
  v_removed_legacy integer := 0;
begin
  perform set_config('zhirox.daftar_sync_guardian','on',true);

  insert into private.daftar_source_fingerprint_aliases(
    sync_source_id,source_fingerprint,alias_kind
  )
  select id,source_fingerprint,'current'
  from public.daftar_sync_sources
  where nullif(source_fingerprint,'') is not null
  on conflict(sync_source_id,source_fingerprint)
  do update set alias_kind='current';

  for r in
    select id,trigger_secret_hash,trigger_secret_vault_name
    from public.daftar_sync_sources
    where enabled=true
    order by created_at,id
  loop
    v_secret := null;

    if nullif(r.trigger_secret_vault_name,'') is not null then
      select decrypted_secret into v_secret
      from vault.decrypted_secrets
      where name=r.trigger_secret_vault_name
      limit 1;
    end if;

    if v_secret is null
       or encode(extensions.digest(v_secret,'sha256'),'hex')
          is distinct from r.trigger_secret_hash then
      v_invalid := v_invalid + 1;

      update public.daftar_sync_sources
      set health_status='degraded',
          last_status='failed',
          last_error='trigger_secret_missing_or_invalid',
          updated_at=now()
      where id=r.id;
    else
      v_valid := v_valid + 1;

      update public.daftar_sync_sources
      set last_error=null,
          updated_at=now()
      where id=r.id
        and last_error='trigger_secret_missing_or_invalid';
    end if;

    perform public.qualify_daftar_outage(r.id);
  end loop;

  for j in
    select jobid
    from cron.job
    where jobname in (
      'daftar-live-sync-account-28',
      'daftar-sync-reconcile-account-28',
      'daily-tenant-backup-account-28',
      'daily-daftar-tenant-backup-all',
      'daftar-sync-guardian-account-28',
      'daftar-outbound-sync-account-28',
      'daftar-sync-dispatch-all',
      'daftar-sync-reconcile-all',
      'daftar-sync-guardian-all'
    )
  loop
    perform cron.unschedule(j.jobid);
    v_removed_legacy := v_removed_legacy + 1;
  end loop;

  select jobid into v_job_id
  from cron.job
  where jobname='daftar-sync-multitenant-dispatch'
  limit 1;

  if v_job_id is null then
    perform cron.schedule(
      'daftar-sync-multitenant-dispatch',
      '* * * * *',
      'select private.dispatch_daftar_sync_sources();'
    );
  else
    perform cron.alter_job(
      job_id=>v_job_id,
      schedule=>'* * * * *',
      command=>'select private.dispatch_daftar_sync_sources();',
      active=>true
    );
  end if;

  select jobid into v_job_id
  from cron.job
  where jobname='daftar-sync-multitenant-reconcile'
  limit 1;

  if v_job_id is null then
    perform cron.schedule(
      'daftar-sync-multitenant-reconcile',
      '17 * * * *',
      'select private.reconcile_daftar_sync_sources();'
    );
  else
    perform cron.alter_job(
      job_id=>v_job_id,
      schedule=>'17 * * * *',
      command=>'select private.reconcile_daftar_sync_sources();',
      active=>true
    );
  end if;

  select jobid into v_job_id
  from cron.job
  where jobname='daftar-sync-multitenant-guardian'
  limit 1;

  if v_job_id is null then
    perform cron.schedule(
      'daftar-sync-multitenant-guardian',
      '* * * * *',
      'select private.guard_daftar_sync_sources();'
    );
  else
    perform cron.alter_job(
      job_id=>v_job_id,
      schedule=>'* * * * *',
      command=>'select private.guard_daftar_sync_sources();',
      active=>true
    );
  end if;

  perform private.guard_backup_runtime();

  return jsonb_build_object(
    'valid_sources',v_valid,
    'invalid_sources',v_invalid,
    'deprecated_jobs_removed',v_removed_legacy,
    'runtime_jobs',3
  );
end;
$function$;

select private.guard_backup_runtime();
