-- Expand employee authorization from 60 to 180 granular permissions.
-- All 120 new permissions default to false (least privilege).

alter table public.profiles
  add column if not exists can_view_customer_documents boolean not null default false,
  add column if not exists can_manage_customer_documents boolean not null default false,
  add column if not exists can_create_customer_qr boolean not null default false,
  add column if not exists can_view_customer_qr boolean not null default false,
  add column if not exists can_archive_customers boolean not null default false,
  add column if not exists can_restore_archived_customers boolean not null default false,
  add column if not exists can_blacklist_customers boolean not null default false,
  add column if not exists can_remove_customer_blacklist boolean not null default false,
  add column if not exists can_approve_new_debts boolean not null default false,
  add column if not exists can_reject_new_debts boolean not null default false,
  add column if not exists can_override_debt_limit boolean not null default false,
  add column if not exists can_change_due_date_after_create boolean not null default false,
  add column if not exists can_close_debts boolean not null default false,
  add column if not exists can_reopen_debts boolean not null default false,
  add column if not exists can_change_debt_currency boolean not null default false,
  add column if not exists can_change_debt_amount_after_approval boolean not null default false,
  add column if not exists can_approve_payments boolean not null default false,
  add column if not exists can_void_payments boolean not null default false,
  add column if not exists can_correct_payment_amount boolean not null default false,
  add column if not exists can_correct_payment_date boolean not null default false,
  add column if not exists can_reallocate_payments boolean not null default false,
  add column if not exists can_restore_voided_payments boolean not null default false,
  add column if not exists can_print_receipts boolean not null default false,
  add column if not exists can_share_receipts boolean not null default false,
  add column if not exists can_reissue_receipts boolean not null default false,
  add column if not exists can_view_receipt_history boolean not null default false,
  add column if not exists can_lock_receipts boolean not null default false,
  add column if not exists can_unlock_receipts boolean not null default false,
  add column if not exists can_suspend_employees boolean not null default false,
  add column if not exists can_reactivate_employees boolean not null default false,
  add column if not exists can_reset_employee_passwords boolean not null default false,
  add column if not exists can_view_employee_login_history boolean not null default false,
  add column if not exists can_force_employee_logout boolean not null default false,
  add column if not exists can_manage_employee_devices boolean not null default false,
  add column if not exists can_pause_sync boolean not null default false,
  add column if not exists can_resume_sync boolean not null default false,
  add column if not exists can_replay_failed_sync boolean not null default false,
  add column if not exists can_view_sync_payloads boolean not null default false,
  add column if not exists can_download_backups boolean not null default false,
  add column if not exists can_export_audit_log boolean not null default false,
  add column if not exists can_view_active_devices boolean not null default false,
  add column if not exists can_remove_trusted_devices boolean not null default false,
  add column if not exists can_approve_new_devices boolean not null default false,
  add column if not exists can_view_failed_logins boolean not null default false,
  add column if not exists can_lock_employee_accounts boolean not null default false,
  add column if not exists can_unlock_employee_accounts boolean not null default false,
  add column if not exists can_force_password_change boolean not null default false,
  add column if not exists can_manage_biometric_login boolean not null default false,
  add column if not exists can_view_deleted_transactions boolean not null default false,
  add column if not exists can_restore_deleted_transactions boolean not null default false,
  add column if not exists can_approve_transaction_edits boolean not null default false,
  add column if not exists can_view_transaction_change_history boolean not null default false,
  add column if not exists can_lock_old_transactions boolean not null default false,
  add column if not exists can_unlock_old_transactions boolean not null default false,
  add column if not exists can_transfer_transactions_between_customers boolean not null default false,
  add column if not exists can_require_transaction_edit_reason boolean not null default false,
  add column if not exists can_view_daily_reports boolean not null default false,
  add column if not exists can_view_weekly_reports boolean not null default false,
  add column if not exists can_view_monthly_reports boolean not null default false,
  add column if not exists can_view_yearly_reports boolean not null default false,
  add column if not exists can_create_custom_reports boolean not null default false,
  add column if not exists can_schedule_reports boolean not null default false,
  add column if not exists can_send_report_notifications boolean not null default false,
  add column if not exists can_view_employee_performance_reports boolean not null default false,
  add column if not exists can_assign_customer_tags boolean not null default false,
  add column if not exists can_manage_customer_tags boolean not null default false,
  add column if not exists can_set_customer_priority boolean not null default false,
  add column if not exists can_set_customer_status boolean not null default false,
  add column if not exists can_create_followups boolean not null default false,
  add column if not exists can_complete_followups boolean not null default false,
  add column if not exists can_view_customer_contact_history boolean not null default false,
  add column if not exists can_add_private_customer_notes boolean not null default false,
  add column if not exists can_view_backend_health boolean not null default false,
  add column if not exists can_view_database_health boolean not null default false,
  add column if not exists can_view_sync_queue boolean not null default false,
  add column if not exists can_clear_cache boolean not null default false,
  add column if not exists can_refresh_configuration boolean not null default false,
  add column if not exists can_view_version_history boolean not null default false,
  add column if not exists can_view_feature_flags boolean not null default false,
  add column if not exists can_manage_feature_flags boolean not null default false,
  add column if not exists can_approve_customer_creation boolean not null default false,
  add column if not exists can_approve_customer_edits boolean not null default false,
  add column if not exists can_approve_customer_deletion boolean not null default false,
  add column if not exists can_approve_debt_edits boolean not null default false,
  add column if not exists can_approve_debt_deletion boolean not null default false,
  add column if not exists can_approve_payment_voids boolean not null default false,
  add column if not exists can_approve_restores boolean not null default false,
  add column if not exists can_approve_debt_limit_changes boolean not null default false,
  add column if not exists can_view_full_phone_numbers boolean not null default false,
  add column if not exists can_view_masked_phone_numbers boolean not null default false,
  add column if not exists can_view_identity_documents boolean not null default false,
  add column if not exists can_download_identity_documents boolean not null default false,
  add column if not exists can_view_private_notes boolean not null default false,
  add column if not exists can_edit_private_notes boolean not null default false,
  add column if not exists can_export_personal_data boolean not null default false,
  add column if not exists can_anonymize_customer_data boolean not null default false,
  add column if not exists can_send_sms boolean not null default false,
  add column if not exists can_send_push_notifications boolean not null default false,
  add column if not exists can_send_telegram_notifications boolean not null default false,
  add column if not exists can_send_whatsapp_templates boolean not null default false,
  add column if not exists can_approve_notifications boolean not null default false,
  add column if not exists can_view_notification_delivery_status boolean not null default false,
  add column if not exists can_retry_failed_notifications boolean not null default false,
  add column if not exists can_lock_bulk_messaging boolean not null default false,
  add column if not exists can_view_api_status boolean not null default false,
  add column if not exists can_manage_api_keys boolean not null default false,
  add column if not exists can_revoke_api_keys boolean not null default false,
  add column if not exists can_view_webhook_logs boolean not null default false,
  add column if not exists can_retry_webhooks boolean not null default false,
  add column if not exists can_disable_integrations boolean not null default false,
  add column if not exists can_enable_integrations boolean not null default false,
  add column if not exists can_view_sync_mappings boolean not null default false,
  add column if not exists can_create_automation_rules boolean not null default false,
  add column if not exists can_edit_automation_rules boolean not null default false,
  add column if not exists can_delete_automation_rules boolean not null default false,
  add column if not exists can_pause_resume_automation boolean not null default false,
  add column if not exists can_view_automation_logs boolean not null default false,
  add column if not exists can_create_alert_rules boolean not null default false,
  add column if not exists can_edit_alert_thresholds boolean not null default false,
  add column if not exists can_mute_alerts boolean not null default false;

alter table public.employee_permissions
  add column if not exists can_view_customer_documents boolean not null default false,
  add column if not exists can_manage_customer_documents boolean not null default false,
  add column if not exists can_create_customer_qr boolean not null default false,
  add column if not exists can_view_customer_qr boolean not null default false,
  add column if not exists can_archive_customers boolean not null default false,
  add column if not exists can_restore_archived_customers boolean not null default false,
  add column if not exists can_blacklist_customers boolean not null default false,
  add column if not exists can_remove_customer_blacklist boolean not null default false,
  add column if not exists can_approve_new_debts boolean not null default false,
  add column if not exists can_reject_new_debts boolean not null default false,
  add column if not exists can_override_debt_limit boolean not null default false,
  add column if not exists can_change_due_date_after_create boolean not null default false,
  add column if not exists can_close_debts boolean not null default false,
  add column if not exists can_reopen_debts boolean not null default false,
  add column if not exists can_change_debt_currency boolean not null default false,
  add column if not exists can_change_debt_amount_after_approval boolean not null default false,
  add column if not exists can_approve_payments boolean not null default false,
  add column if not exists can_void_payments boolean not null default false,
  add column if not exists can_correct_payment_amount boolean not null default false,
  add column if not exists can_correct_payment_date boolean not null default false,
  add column if not exists can_reallocate_payments boolean not null default false,
  add column if not exists can_restore_voided_payments boolean not null default false,
  add column if not exists can_print_receipts boolean not null default false,
  add column if not exists can_share_receipts boolean not null default false,
  add column if not exists can_reissue_receipts boolean not null default false,
  add column if not exists can_view_receipt_history boolean not null default false,
  add column if not exists can_lock_receipts boolean not null default false,
  add column if not exists can_unlock_receipts boolean not null default false,
  add column if not exists can_suspend_employees boolean not null default false,
  add column if not exists can_reactivate_employees boolean not null default false,
  add column if not exists can_reset_employee_passwords boolean not null default false,
  add column if not exists can_view_employee_login_history boolean not null default false,
  add column if not exists can_force_employee_logout boolean not null default false,
  add column if not exists can_manage_employee_devices boolean not null default false,
  add column if not exists can_pause_sync boolean not null default false,
  add column if not exists can_resume_sync boolean not null default false,
  add column if not exists can_replay_failed_sync boolean not null default false,
  add column if not exists can_view_sync_payloads boolean not null default false,
  add column if not exists can_download_backups boolean not null default false,
  add column if not exists can_export_audit_log boolean not null default false,
  add column if not exists can_view_active_devices boolean not null default false,
  add column if not exists can_remove_trusted_devices boolean not null default false,
  add column if not exists can_approve_new_devices boolean not null default false,
  add column if not exists can_view_failed_logins boolean not null default false,
  add column if not exists can_lock_employee_accounts boolean not null default false,
  add column if not exists can_unlock_employee_accounts boolean not null default false,
  add column if not exists can_force_password_change boolean not null default false,
  add column if not exists can_manage_biometric_login boolean not null default false,
  add column if not exists can_view_deleted_transactions boolean not null default false,
  add column if not exists can_restore_deleted_transactions boolean not null default false,
  add column if not exists can_approve_transaction_edits boolean not null default false,
  add column if not exists can_view_transaction_change_history boolean not null default false,
  add column if not exists can_lock_old_transactions boolean not null default false,
  add column if not exists can_unlock_old_transactions boolean not null default false,
  add column if not exists can_transfer_transactions_between_customers boolean not null default false,
  add column if not exists can_require_transaction_edit_reason boolean not null default false,
  add column if not exists can_view_daily_reports boolean not null default false,
  add column if not exists can_view_weekly_reports boolean not null default false,
  add column if not exists can_view_monthly_reports boolean not null default false,
  add column if not exists can_view_yearly_reports boolean not null default false,
  add column if not exists can_create_custom_reports boolean not null default false,
  add column if not exists can_schedule_reports boolean not null default false,
  add column if not exists can_send_report_notifications boolean not null default false,
  add column if not exists can_view_employee_performance_reports boolean not null default false,
  add column if not exists can_assign_customer_tags boolean not null default false,
  add column if not exists can_manage_customer_tags boolean not null default false,
  add column if not exists can_set_customer_priority boolean not null default false,
  add column if not exists can_set_customer_status boolean not null default false,
  add column if not exists can_create_followups boolean not null default false,
  add column if not exists can_complete_followups boolean not null default false,
  add column if not exists can_view_customer_contact_history boolean not null default false,
  add column if not exists can_add_private_customer_notes boolean not null default false,
  add column if not exists can_view_backend_health boolean not null default false,
  add column if not exists can_view_database_health boolean not null default false,
  add column if not exists can_view_sync_queue boolean not null default false,
  add column if not exists can_clear_cache boolean not null default false,
  add column if not exists can_refresh_configuration boolean not null default false,
  add column if not exists can_view_version_history boolean not null default false,
  add column if not exists can_view_feature_flags boolean not null default false,
  add column if not exists can_manage_feature_flags boolean not null default false,
  add column if not exists can_approve_customer_creation boolean not null default false,
  add column if not exists can_approve_customer_edits boolean not null default false,
  add column if not exists can_approve_customer_deletion boolean not null default false,
  add column if not exists can_approve_debt_edits boolean not null default false,
  add column if not exists can_approve_debt_deletion boolean not null default false,
  add column if not exists can_approve_payment_voids boolean not null default false,
  add column if not exists can_approve_restores boolean not null default false,
  add column if not exists can_approve_debt_limit_changes boolean not null default false,
  add column if not exists can_view_full_phone_numbers boolean not null default false,
  add column if not exists can_view_masked_phone_numbers boolean not null default false,
  add column if not exists can_view_identity_documents boolean not null default false,
  add column if not exists can_download_identity_documents boolean not null default false,
  add column if not exists can_view_private_notes boolean not null default false,
  add column if not exists can_edit_private_notes boolean not null default false,
  add column if not exists can_export_personal_data boolean not null default false,
  add column if not exists can_anonymize_customer_data boolean not null default false,
  add column if not exists can_send_sms boolean not null default false,
  add column if not exists can_send_push_notifications boolean not null default false,
  add column if not exists can_send_telegram_notifications boolean not null default false,
  add column if not exists can_send_whatsapp_templates boolean not null default false,
  add column if not exists can_approve_notifications boolean not null default false,
  add column if not exists can_view_notification_delivery_status boolean not null default false,
  add column if not exists can_retry_failed_notifications boolean not null default false,
  add column if not exists can_lock_bulk_messaging boolean not null default false,
  add column if not exists can_view_api_status boolean not null default false,
  add column if not exists can_manage_api_keys boolean not null default false,
  add column if not exists can_revoke_api_keys boolean not null default false,
  add column if not exists can_view_webhook_logs boolean not null default false,
  add column if not exists can_retry_webhooks boolean not null default false,
  add column if not exists can_disable_integrations boolean not null default false,
  add column if not exists can_enable_integrations boolean not null default false,
  add column if not exists can_view_sync_mappings boolean not null default false,
  add column if not exists can_create_automation_rules boolean not null default false,
  add column if not exists can_edit_automation_rules boolean not null default false,
  add column if not exists can_delete_automation_rules boolean not null default false,
  add column if not exists can_pause_resume_automation boolean not null default false,
  add column if not exists can_view_automation_logs boolean not null default false,
  add column if not exists can_create_alert_rules boolean not null default false,
  add column if not exists can_edit_alert_thresholds boolean not null default false,
  add column if not exists can_mute_alerts boolean not null default false;

create or replace function public.set_employee_permissions_v2(
  p_employee_id uuid,
  p_permissions jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  requester public.profiles%rowtype;
  allowed_columns constant text[] := array[
    'can_view_customers',
    'can_add_customers',
    'can_edit_customers',
    'can_delete_customers',
    'can_approve_customers',
    'can_manage_customer_links',
    'can_pin_customers',
    'can_manage_vip_customers',
    'can_merge_customer_identities',
    'can_view_customer_phone',
    'can_view_customer_notes',
    'can_edit_customer_notes',
    'can_view_customer_balances',
    'can_view_debts',
    'can_add_debts',
    'can_edit_debts',
    'can_delete_debts',
    'can_record_payments',
    'can_set_debt_limit',
    'can_set_due_date',
    'can_refund_payments',
    'can_restore_debts',
    'can_view_transactions',
    'can_edit_payments',
    'can_delete_payments',
    'can_view_payment_history',
    'can_manage_collections',
    'can_view_financial_reports',
    'can_export_data',
    'can_import_data',
    'can_manage_receipts',
    'can_create_statements',
    'can_create_receipts',
    'can_edit_receipts',
    'can_delete_receipts',
    'can_export_receipts',
    'can_view_report_summary',
    'can_export_reports',
    'can_send_notifications',
    'can_manage_notifications',
    'can_manage_notification_templates',
    'can_send_bulk_notifications',
    'can_manage_employees',
    'can_view_audit_log',
    'can_manage_backup',
    'can_run_manual_backup',
    'can_restore_backup',
    'can_manage_daftar_sync',
    'can_view_sync_logs',
    'can_retry_failed_sync',
    'can_manage_subscription',
    'can_view_dashboard',
    'can_view_recent_activity',
    'can_view_market_rates',
    'can_manage_market_rate_refresh',
    'can_view_intelligence',
    'can_view_expiry',
    'can_manage_expiry',
    'can_manage_settings',
    'can_manage_security_settings',
    'can_view_customer_documents',
    'can_manage_customer_documents',
    'can_create_customer_qr',
    'can_view_customer_qr',
    'can_archive_customers',
    'can_restore_archived_customers',
    'can_blacklist_customers',
    'can_remove_customer_blacklist',
    'can_approve_new_debts',
    'can_reject_new_debts',
    'can_override_debt_limit',
    'can_change_due_date_after_create',
    'can_close_debts',
    'can_reopen_debts',
    'can_change_debt_currency',
    'can_change_debt_amount_after_approval',
    'can_approve_payments',
    'can_void_payments',
    'can_correct_payment_amount',
    'can_correct_payment_date',
    'can_reallocate_payments',
    'can_restore_voided_payments',
    'can_print_receipts',
    'can_share_receipts',
    'can_reissue_receipts',
    'can_view_receipt_history',
    'can_lock_receipts',
    'can_unlock_receipts',
    'can_suspend_employees',
    'can_reactivate_employees',
    'can_reset_employee_passwords',
    'can_view_employee_login_history',
    'can_force_employee_logout',
    'can_manage_employee_devices',
    'can_pause_sync',
    'can_resume_sync',
    'can_replay_failed_sync',
    'can_view_sync_payloads',
    'can_download_backups',
    'can_export_audit_log',
    'can_view_active_devices',
    'can_remove_trusted_devices',
    'can_approve_new_devices',
    'can_view_failed_logins',
    'can_lock_employee_accounts',
    'can_unlock_employee_accounts',
    'can_force_password_change',
    'can_manage_biometric_login',
    'can_view_deleted_transactions',
    'can_restore_deleted_transactions',
    'can_approve_transaction_edits',
    'can_view_transaction_change_history',
    'can_lock_old_transactions',
    'can_unlock_old_transactions',
    'can_transfer_transactions_between_customers',
    'can_require_transaction_edit_reason',
    'can_view_daily_reports',
    'can_view_weekly_reports',
    'can_view_monthly_reports',
    'can_view_yearly_reports',
    'can_create_custom_reports',
    'can_schedule_reports',
    'can_send_report_notifications',
    'can_view_employee_performance_reports',
    'can_assign_customer_tags',
    'can_manage_customer_tags',
    'can_set_customer_priority',
    'can_set_customer_status',
    'can_create_followups',
    'can_complete_followups',
    'can_view_customer_contact_history',
    'can_add_private_customer_notes',
    'can_view_backend_health',
    'can_view_database_health',
    'can_view_sync_queue',
    'can_clear_cache',
    'can_refresh_configuration',
    'can_view_version_history',
    'can_view_feature_flags',
    'can_manage_feature_flags',
    'can_approve_customer_creation',
    'can_approve_customer_edits',
    'can_approve_customer_deletion',
    'can_approve_debt_edits',
    'can_approve_debt_deletion',
    'can_approve_payment_voids',
    'can_approve_restores',
    'can_approve_debt_limit_changes',
    'can_view_full_phone_numbers',
    'can_view_masked_phone_numbers',
    'can_view_identity_documents',
    'can_download_identity_documents',
    'can_view_private_notes',
    'can_edit_private_notes',
    'can_export_personal_data',
    'can_anonymize_customer_data',
    'can_send_sms',
    'can_send_push_notifications',
    'can_send_telegram_notifications',
    'can_send_whatsapp_templates',
    'can_approve_notifications',
    'can_view_notification_delivery_status',
    'can_retry_failed_notifications',
    'can_lock_bulk_messaging',
    'can_view_api_status',
    'can_manage_api_keys',
    'can_revoke_api_keys',
    'can_view_webhook_logs',
    'can_retry_webhooks',
    'can_disable_integrations',
    'can_enable_integrations',
    'can_view_sync_mappings',
    'can_create_automation_rules',
    'can_edit_automation_rules',
    'can_delete_automation_rules',
    'can_pause_resume_automation',
    'can_view_automation_logs',
    'can_create_alert_rules',
    'can_edit_alert_thresholds',
    'can_mute_alerts'
  ];
  invalid_key text;
  invalid_type text;
  set_clause text;
begin
  if auth.uid() is null then
    raise exception 'authentication_required' using errcode = '42501';
  end if;

  select * into requester
  from public.profiles
  where id = auth.uid();

  if requester.id is null
     or requester.role <> 'admin'
     or requester.active is not true
     or requester.approved is not true then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  if not exists (
    select 1 from public.profiles p
    where p.id = p_employee_id
      and p.role = 'employee'
      and p.admin_id = requester.id
  ) then
    raise exception 'employee_not_found_or_forbidden' using errcode = '42501';
  end if;

  if p_permissions is null or jsonb_typeof(p_permissions) <> 'object' then
    raise exception 'invalid_permissions_payload' using errcode = '22023';
  end if;

  select key into invalid_key
  from jsonb_object_keys(p_permissions) key
  where not (key = any(allowed_columns))
  limit 1;
  if invalid_key is not null then
    raise exception 'unknown_permission:%', invalid_key using errcode = '22023';
  end if;

  select e.key into invalid_type
  from jsonb_each(p_permissions) e
  where jsonb_typeof(e.value) <> 'boolean'
  limit 1;
  if invalid_type is not null then
    raise exception 'permission_must_be_boolean:%', invalid_type using errcode = '22023';
  end if;

  select string_agg(format('%I = %L::boolean', e.key, e.value #>> '{}'), ', ')
    into set_clause
  from jsonb_each(p_permissions) e;

  if set_clause is null or btrim(set_clause) = '' then return; end if;

  execute format(
    'update public.profiles set %s, updated_at = now() where id = $1',
    set_clause
  ) using p_employee_id;

  execute format(
    'update public.employee_permissions set %s, updated_at = now(), updated_by = $1 where employee_id = $2 and admin_id = $1',
    set_clause
  ) using requester.id, p_employee_id;
end;
$function$;

revoke all on function public.set_employee_permissions_v2(uuid, jsonb) from public, anon;
grant execute on function public.set_employee_permissions_v2(uuid, jsonb) to authenticated;

create or replace function private.sync_employee_permissions_to_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if pg_trigger_depth() > 1 then return new; end if;
  update public.profiles
  set can_view_customers = new.can_view_customers,
      can_add_customers = new.can_add_customers,
      can_edit_customers = new.can_edit_customers,
      can_delete_customers = new.can_delete_customers,
      can_approve_customers = new.can_approve_customers,
      can_manage_customer_links = new.can_manage_customer_links,
      can_pin_customers = new.can_pin_customers,
      can_manage_vip_customers = new.can_manage_vip_customers,
      can_merge_customer_identities = new.can_merge_customer_identities,
      can_view_customer_phone = new.can_view_customer_phone,
      can_view_customer_notes = new.can_view_customer_notes,
      can_edit_customer_notes = new.can_edit_customer_notes,
      can_view_customer_balances = new.can_view_customer_balances,
      can_view_debts = new.can_view_debts,
      can_add_debts = new.can_add_debts,
      can_edit_debts = new.can_edit_debts,
      can_delete_debts = new.can_delete_debts,
      can_record_payments = new.can_record_payments,
      can_set_debt_limit = new.can_set_debt_limit,
      can_set_due_date = new.can_set_due_date,
      can_refund_payments = new.can_refund_payments,
      can_restore_debts = new.can_restore_debts,
      can_view_transactions = new.can_view_transactions,
      can_edit_payments = new.can_edit_payments,
      can_delete_payments = new.can_delete_payments,
      can_view_payment_history = new.can_view_payment_history,
      can_manage_collections = new.can_manage_collections,
      can_view_financial_reports = new.can_view_financial_reports,
      can_export_data = new.can_export_data,
      can_import_data = new.can_import_data,
      can_manage_receipts = new.can_manage_receipts,
      can_create_statements = new.can_create_statements,
      can_create_receipts = new.can_create_receipts,
      can_edit_receipts = new.can_edit_receipts,
      can_delete_receipts = new.can_delete_receipts,
      can_export_receipts = new.can_export_receipts,
      can_view_report_summary = new.can_view_report_summary,
      can_export_reports = new.can_export_reports,
      can_send_notifications = new.can_send_notifications,
      can_manage_notifications = new.can_manage_notifications,
      can_manage_notification_templates = new.can_manage_notification_templates,
      can_send_bulk_notifications = new.can_send_bulk_notifications,
      can_manage_employees = new.can_manage_employees,
      can_view_audit_log = new.can_view_audit_log,
      can_manage_backup = new.can_manage_backup,
      can_run_manual_backup = new.can_run_manual_backup,
      can_restore_backup = new.can_restore_backup,
      can_manage_daftar_sync = new.can_manage_daftar_sync,
      can_view_sync_logs = new.can_view_sync_logs,
      can_retry_failed_sync = new.can_retry_failed_sync,
      can_manage_subscription = new.can_manage_subscription,
      can_view_dashboard = new.can_view_dashboard,
      can_view_recent_activity = new.can_view_recent_activity,
      can_view_market_rates = new.can_view_market_rates,
      can_manage_market_rate_refresh = new.can_manage_market_rate_refresh,
      can_view_intelligence = new.can_view_intelligence,
      can_view_expiry = new.can_view_expiry,
      can_manage_expiry = new.can_manage_expiry,
      can_manage_settings = new.can_manage_settings,
      can_manage_security_settings = new.can_manage_security_settings,
      can_view_customer_documents = new.can_view_customer_documents,
      can_manage_customer_documents = new.can_manage_customer_documents,
      can_create_customer_qr = new.can_create_customer_qr,
      can_view_customer_qr = new.can_view_customer_qr,
      can_archive_customers = new.can_archive_customers,
      can_restore_archived_customers = new.can_restore_archived_customers,
      can_blacklist_customers = new.can_blacklist_customers,
      can_remove_customer_blacklist = new.can_remove_customer_blacklist,
      can_approve_new_debts = new.can_approve_new_debts,
      can_reject_new_debts = new.can_reject_new_debts,
      can_override_debt_limit = new.can_override_debt_limit,
      can_change_due_date_after_create = new.can_change_due_date_after_create,
      can_close_debts = new.can_close_debts,
      can_reopen_debts = new.can_reopen_debts,
      can_change_debt_currency = new.can_change_debt_currency,
      can_change_debt_amount_after_approval = new.can_change_debt_amount_after_approval,
      can_approve_payments = new.can_approve_payments,
      can_void_payments = new.can_void_payments,
      can_correct_payment_amount = new.can_correct_payment_amount,
      can_correct_payment_date = new.can_correct_payment_date,
      can_reallocate_payments = new.can_reallocate_payments,
      can_restore_voided_payments = new.can_restore_voided_payments,
      can_print_receipts = new.can_print_receipts,
      can_share_receipts = new.can_share_receipts,
      can_reissue_receipts = new.can_reissue_receipts,
      can_view_receipt_history = new.can_view_receipt_history,
      can_lock_receipts = new.can_lock_receipts,
      can_unlock_receipts = new.can_unlock_receipts,
      can_suspend_employees = new.can_suspend_employees,
      can_reactivate_employees = new.can_reactivate_employees,
      can_reset_employee_passwords = new.can_reset_employee_passwords,
      can_view_employee_login_history = new.can_view_employee_login_history,
      can_force_employee_logout = new.can_force_employee_logout,
      can_manage_employee_devices = new.can_manage_employee_devices,
      can_pause_sync = new.can_pause_sync,
      can_resume_sync = new.can_resume_sync,
      can_replay_failed_sync = new.can_replay_failed_sync,
      can_view_sync_payloads = new.can_view_sync_payloads,
      can_download_backups = new.can_download_backups,
      can_export_audit_log = new.can_export_audit_log,
      can_view_active_devices = new.can_view_active_devices,
      can_remove_trusted_devices = new.can_remove_trusted_devices,
      can_approve_new_devices = new.can_approve_new_devices,
      can_view_failed_logins = new.can_view_failed_logins,
      can_lock_employee_accounts = new.can_lock_employee_accounts,
      can_unlock_employee_accounts = new.can_unlock_employee_accounts,
      can_force_password_change = new.can_force_password_change,
      can_manage_biometric_login = new.can_manage_biometric_login,
      can_view_deleted_transactions = new.can_view_deleted_transactions,
      can_restore_deleted_transactions = new.can_restore_deleted_transactions,
      can_approve_transaction_edits = new.can_approve_transaction_edits,
      can_view_transaction_change_history = new.can_view_transaction_change_history,
      can_lock_old_transactions = new.can_lock_old_transactions,
      can_unlock_old_transactions = new.can_unlock_old_transactions,
      can_transfer_transactions_between_customers = new.can_transfer_transactions_between_customers,
      can_require_transaction_edit_reason = new.can_require_transaction_edit_reason,
      can_view_daily_reports = new.can_view_daily_reports,
      can_view_weekly_reports = new.can_view_weekly_reports,
      can_view_monthly_reports = new.can_view_monthly_reports,
      can_view_yearly_reports = new.can_view_yearly_reports,
      can_create_custom_reports = new.can_create_custom_reports,
      can_schedule_reports = new.can_schedule_reports,
      can_send_report_notifications = new.can_send_report_notifications,
      can_view_employee_performance_reports = new.can_view_employee_performance_reports,
      can_assign_customer_tags = new.can_assign_customer_tags,
      can_manage_customer_tags = new.can_manage_customer_tags,
      can_set_customer_priority = new.can_set_customer_priority,
      can_set_customer_status = new.can_set_customer_status,
      can_create_followups = new.can_create_followups,
      can_complete_followups = new.can_complete_followups,
      can_view_customer_contact_history = new.can_view_customer_contact_history,
      can_add_private_customer_notes = new.can_add_private_customer_notes,
      can_view_backend_health = new.can_view_backend_health,
      can_view_database_health = new.can_view_database_health,
      can_view_sync_queue = new.can_view_sync_queue,
      can_clear_cache = new.can_clear_cache,
      can_refresh_configuration = new.can_refresh_configuration,
      can_view_version_history = new.can_view_version_history,
      can_view_feature_flags = new.can_view_feature_flags,
      can_manage_feature_flags = new.can_manage_feature_flags,
      can_approve_customer_creation = new.can_approve_customer_creation,
      can_approve_customer_edits = new.can_approve_customer_edits,
      can_approve_customer_deletion = new.can_approve_customer_deletion,
      can_approve_debt_edits = new.can_approve_debt_edits,
      can_approve_debt_deletion = new.can_approve_debt_deletion,
      can_approve_payment_voids = new.can_approve_payment_voids,
      can_approve_restores = new.can_approve_restores,
      can_approve_debt_limit_changes = new.can_approve_debt_limit_changes,
      can_view_full_phone_numbers = new.can_view_full_phone_numbers,
      can_view_masked_phone_numbers = new.can_view_masked_phone_numbers,
      can_view_identity_documents = new.can_view_identity_documents,
      can_download_identity_documents = new.can_download_identity_documents,
      can_view_private_notes = new.can_view_private_notes,
      can_edit_private_notes = new.can_edit_private_notes,
      can_export_personal_data = new.can_export_personal_data,
      can_anonymize_customer_data = new.can_anonymize_customer_data,
      can_send_sms = new.can_send_sms,
      can_send_push_notifications = new.can_send_push_notifications,
      can_send_telegram_notifications = new.can_send_telegram_notifications,
      can_send_whatsapp_templates = new.can_send_whatsapp_templates,
      can_approve_notifications = new.can_approve_notifications,
      can_view_notification_delivery_status = new.can_view_notification_delivery_status,
      can_retry_failed_notifications = new.can_retry_failed_notifications,
      can_lock_bulk_messaging = new.can_lock_bulk_messaging,
      can_view_api_status = new.can_view_api_status,
      can_manage_api_keys = new.can_manage_api_keys,
      can_revoke_api_keys = new.can_revoke_api_keys,
      can_view_webhook_logs = new.can_view_webhook_logs,
      can_retry_webhooks = new.can_retry_webhooks,
      can_disable_integrations = new.can_disable_integrations,
      can_enable_integrations = new.can_enable_integrations,
      can_view_sync_mappings = new.can_view_sync_mappings,
      can_create_automation_rules = new.can_create_automation_rules,
      can_edit_automation_rules = new.can_edit_automation_rules,
      can_delete_automation_rules = new.can_delete_automation_rules,
      can_pause_resume_automation = new.can_pause_resume_automation,
      can_view_automation_logs = new.can_view_automation_logs,
      can_create_alert_rules = new.can_create_alert_rules,
      can_edit_alert_thresholds = new.can_edit_alert_thresholds,
      can_mute_alerts = new.can_mute_alerts,
      updated_at = now()
  where id = new.employee_id
    and role = 'employee'
    and admin_id = new.admin_id;
  return new;
end;
$function$;

create or replace function private.sync_profile_permissions_to_employee_permissions()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if pg_trigger_depth() > 1 then return new; end if;

  if new.role = 'employee' and new.admin_id is not null then
    insert into public.employee_permissions (
      employee_id,
      admin_id,
      can_view_customers,
      can_add_customers,
      can_edit_customers,
      can_delete_customers,
      can_approve_customers,
      can_manage_customer_links,
      can_pin_customers,
      can_manage_vip_customers,
      can_merge_customer_identities,
      can_view_customer_phone,
      can_view_customer_notes,
      can_edit_customer_notes,
      can_view_customer_balances,
      can_view_debts,
      can_add_debts,
      can_edit_debts,
      can_delete_debts,
      can_record_payments,
      can_set_debt_limit,
      can_set_due_date,
      can_refund_payments,
      can_restore_debts,
      can_view_transactions,
      can_edit_payments,
      can_delete_payments,
      can_view_payment_history,
      can_manage_collections,
      can_view_financial_reports,
      can_export_data,
      can_import_data,
      can_manage_receipts,
      can_create_statements,
      can_create_receipts,
      can_edit_receipts,
      can_delete_receipts,
      can_export_receipts,
      can_view_report_summary,
      can_export_reports,
      can_send_notifications,
      can_manage_notifications,
      can_manage_notification_templates,
      can_send_bulk_notifications,
      can_manage_employees,
      can_view_audit_log,
      can_manage_backup,
      can_run_manual_backup,
      can_restore_backup,
      can_manage_daftar_sync,
      can_view_sync_logs,
      can_retry_failed_sync,
      can_manage_subscription,
      can_view_dashboard,
      can_view_recent_activity,
      can_view_market_rates,
      can_manage_market_rate_refresh,
      can_view_intelligence,
      can_view_expiry,
      can_manage_expiry,
      can_manage_settings,
      can_manage_security_settings,
      can_view_customer_documents,
      can_manage_customer_documents,
      can_create_customer_qr,
      can_view_customer_qr,
      can_archive_customers,
      can_restore_archived_customers,
      can_blacklist_customers,
      can_remove_customer_blacklist,
      can_approve_new_debts,
      can_reject_new_debts,
      can_override_debt_limit,
      can_change_due_date_after_create,
      can_close_debts,
      can_reopen_debts,
      can_change_debt_currency,
      can_change_debt_amount_after_approval,
      can_approve_payments,
      can_void_payments,
      can_correct_payment_amount,
      can_correct_payment_date,
      can_reallocate_payments,
      can_restore_voided_payments,
      can_print_receipts,
      can_share_receipts,
      can_reissue_receipts,
      can_view_receipt_history,
      can_lock_receipts,
      can_unlock_receipts,
      can_suspend_employees,
      can_reactivate_employees,
      can_reset_employee_passwords,
      can_view_employee_login_history,
      can_force_employee_logout,
      can_manage_employee_devices,
      can_pause_sync,
      can_resume_sync,
      can_replay_failed_sync,
      can_view_sync_payloads,
      can_download_backups,
      can_export_audit_log,
      can_view_active_devices,
      can_remove_trusted_devices,
      can_approve_new_devices,
      can_view_failed_logins,
      can_lock_employee_accounts,
      can_unlock_employee_accounts,
      can_force_password_change,
      can_manage_biometric_login,
      can_view_deleted_transactions,
      can_restore_deleted_transactions,
      can_approve_transaction_edits,
      can_view_transaction_change_history,
      can_lock_old_transactions,
      can_unlock_old_transactions,
      can_transfer_transactions_between_customers,
      can_require_transaction_edit_reason,
      can_view_daily_reports,
      can_view_weekly_reports,
      can_view_monthly_reports,
      can_view_yearly_reports,
      can_create_custom_reports,
      can_schedule_reports,
      can_send_report_notifications,
      can_view_employee_performance_reports,
      can_assign_customer_tags,
      can_manage_customer_tags,
      can_set_customer_priority,
      can_set_customer_status,
      can_create_followups,
      can_complete_followups,
      can_view_customer_contact_history,
      can_add_private_customer_notes,
      can_view_backend_health,
      can_view_database_health,
      can_view_sync_queue,
      can_clear_cache,
      can_refresh_configuration,
      can_view_version_history,
      can_view_feature_flags,
      can_manage_feature_flags,
      can_approve_customer_creation,
      can_approve_customer_edits,
      can_approve_customer_deletion,
      can_approve_debt_edits,
      can_approve_debt_deletion,
      can_approve_payment_voids,
      can_approve_restores,
      can_approve_debt_limit_changes,
      can_view_full_phone_numbers,
      can_view_masked_phone_numbers,
      can_view_identity_documents,
      can_download_identity_documents,
      can_view_private_notes,
      can_edit_private_notes,
      can_export_personal_data,
      can_anonymize_customer_data,
      can_send_sms,
      can_send_push_notifications,
      can_send_telegram_notifications,
      can_send_whatsapp_templates,
      can_approve_notifications,
      can_view_notification_delivery_status,
      can_retry_failed_notifications,
      can_lock_bulk_messaging,
      can_view_api_status,
      can_manage_api_keys,
      can_revoke_api_keys,
      can_view_webhook_logs,
      can_retry_webhooks,
      can_disable_integrations,
      can_enable_integrations,
      can_view_sync_mappings,
      can_create_automation_rules,
      can_edit_automation_rules,
      can_delete_automation_rules,
      can_pause_resume_automation,
      can_view_automation_logs,
      can_create_alert_rules,
      can_edit_alert_thresholds,
      can_mute_alerts,
      updated_at,
      updated_by
    ) values (
      new.id,
      new.admin_id,
      new.can_view_customers,
      new.can_add_customers,
      new.can_edit_customers,
      new.can_delete_customers,
      new.can_approve_customers,
      new.can_manage_customer_links,
      new.can_pin_customers,
      new.can_manage_vip_customers,
      new.can_merge_customer_identities,
      new.can_view_customer_phone,
      new.can_view_customer_notes,
      new.can_edit_customer_notes,
      new.can_view_customer_balances,
      new.can_view_debts,
      new.can_add_debts,
      new.can_edit_debts,
      new.can_delete_debts,
      new.can_record_payments,
      new.can_set_debt_limit,
      new.can_set_due_date,
      new.can_refund_payments,
      new.can_restore_debts,
      new.can_view_transactions,
      new.can_edit_payments,
      new.can_delete_payments,
      new.can_view_payment_history,
      new.can_manage_collections,
      new.can_view_financial_reports,
      new.can_export_data,
      new.can_import_data,
      new.can_manage_receipts,
      new.can_create_statements,
      new.can_create_receipts,
      new.can_edit_receipts,
      new.can_delete_receipts,
      new.can_export_receipts,
      new.can_view_report_summary,
      new.can_export_reports,
      new.can_send_notifications,
      new.can_manage_notifications,
      new.can_manage_notification_templates,
      new.can_send_bulk_notifications,
      new.can_manage_employees,
      new.can_view_audit_log,
      new.can_manage_backup,
      new.can_run_manual_backup,
      new.can_restore_backup,
      new.can_manage_daftar_sync,
      new.can_view_sync_logs,
      new.can_retry_failed_sync,
      new.can_manage_subscription,
      new.can_view_dashboard,
      new.can_view_recent_activity,
      new.can_view_market_rates,
      new.can_manage_market_rate_refresh,
      new.can_view_intelligence,
      new.can_view_expiry,
      new.can_manage_expiry,
      new.can_manage_settings,
      new.can_manage_security_settings,
      new.can_view_customer_documents,
      new.can_manage_customer_documents,
      new.can_create_customer_qr,
      new.can_view_customer_qr,
      new.can_archive_customers,
      new.can_restore_archived_customers,
      new.can_blacklist_customers,
      new.can_remove_customer_blacklist,
      new.can_approve_new_debts,
      new.can_reject_new_debts,
      new.can_override_debt_limit,
      new.can_change_due_date_after_create,
      new.can_close_debts,
      new.can_reopen_debts,
      new.can_change_debt_currency,
      new.can_change_debt_amount_after_approval,
      new.can_approve_payments,
      new.can_void_payments,
      new.can_correct_payment_amount,
      new.can_correct_payment_date,
      new.can_reallocate_payments,
      new.can_restore_voided_payments,
      new.can_print_receipts,
      new.can_share_receipts,
      new.can_reissue_receipts,
      new.can_view_receipt_history,
      new.can_lock_receipts,
      new.can_unlock_receipts,
      new.can_suspend_employees,
      new.can_reactivate_employees,
      new.can_reset_employee_passwords,
      new.can_view_employee_login_history,
      new.can_force_employee_logout,
      new.can_manage_employee_devices,
      new.can_pause_sync,
      new.can_resume_sync,
      new.can_replay_failed_sync,
      new.can_view_sync_payloads,
      new.can_download_backups,
      new.can_export_audit_log,
      new.can_view_active_devices,
      new.can_remove_trusted_devices,
      new.can_approve_new_devices,
      new.can_view_failed_logins,
      new.can_lock_employee_accounts,
      new.can_unlock_employee_accounts,
      new.can_force_password_change,
      new.can_manage_biometric_login,
      new.can_view_deleted_transactions,
      new.can_restore_deleted_transactions,
      new.can_approve_transaction_edits,
      new.can_view_transaction_change_history,
      new.can_lock_old_transactions,
      new.can_unlock_old_transactions,
      new.can_transfer_transactions_between_customers,
      new.can_require_transaction_edit_reason,
      new.can_view_daily_reports,
      new.can_view_weekly_reports,
      new.can_view_monthly_reports,
      new.can_view_yearly_reports,
      new.can_create_custom_reports,
      new.can_schedule_reports,
      new.can_send_report_notifications,
      new.can_view_employee_performance_reports,
      new.can_assign_customer_tags,
      new.can_manage_customer_tags,
      new.can_set_customer_priority,
      new.can_set_customer_status,
      new.can_create_followups,
      new.can_complete_followups,
      new.can_view_customer_contact_history,
      new.can_add_private_customer_notes,
      new.can_view_backend_health,
      new.can_view_database_health,
      new.can_view_sync_queue,
      new.can_clear_cache,
      new.can_refresh_configuration,
      new.can_view_version_history,
      new.can_view_feature_flags,
      new.can_manage_feature_flags,
      new.can_approve_customer_creation,
      new.can_approve_customer_edits,
      new.can_approve_customer_deletion,
      new.can_approve_debt_edits,
      new.can_approve_debt_deletion,
      new.can_approve_payment_voids,
      new.can_approve_restores,
      new.can_approve_debt_limit_changes,
      new.can_view_full_phone_numbers,
      new.can_view_masked_phone_numbers,
      new.can_view_identity_documents,
      new.can_download_identity_documents,
      new.can_view_private_notes,
      new.can_edit_private_notes,
      new.can_export_personal_data,
      new.can_anonymize_customer_data,
      new.can_send_sms,
      new.can_send_push_notifications,
      new.can_send_telegram_notifications,
      new.can_send_whatsapp_templates,
      new.can_approve_notifications,
      new.can_view_notification_delivery_status,
      new.can_retry_failed_notifications,
      new.can_lock_bulk_messaging,
      new.can_view_api_status,
      new.can_manage_api_keys,
      new.can_revoke_api_keys,
      new.can_view_webhook_logs,
      new.can_retry_webhooks,
      new.can_disable_integrations,
      new.can_enable_integrations,
      new.can_view_sync_mappings,
      new.can_create_automation_rules,
      new.can_edit_automation_rules,
      new.can_delete_automation_rules,
      new.can_pause_resume_automation,
      new.can_view_automation_logs,
      new.can_create_alert_rules,
      new.can_edit_alert_thresholds,
      new.can_mute_alerts,
      now(),
      auth.uid()
    )
    on conflict (employee_id) do update set
      admin_id = excluded.admin_id,
      can_view_customers = excluded.can_view_customers,
      can_add_customers = excluded.can_add_customers,
      can_edit_customers = excluded.can_edit_customers,
      can_delete_customers = excluded.can_delete_customers,
      can_approve_customers = excluded.can_approve_customers,
      can_manage_customer_links = excluded.can_manage_customer_links,
      can_pin_customers = excluded.can_pin_customers,
      can_manage_vip_customers = excluded.can_manage_vip_customers,
      can_merge_customer_identities = excluded.can_merge_customer_identities,
      can_view_customer_phone = excluded.can_view_customer_phone,
      can_view_customer_notes = excluded.can_view_customer_notes,
      can_edit_customer_notes = excluded.can_edit_customer_notes,
      can_view_customer_balances = excluded.can_view_customer_balances,
      can_view_debts = excluded.can_view_debts,
      can_add_debts = excluded.can_add_debts,
      can_edit_debts = excluded.can_edit_debts,
      can_delete_debts = excluded.can_delete_debts,
      can_record_payments = excluded.can_record_payments,
      can_set_debt_limit = excluded.can_set_debt_limit,
      can_set_due_date = excluded.can_set_due_date,
      can_refund_payments = excluded.can_refund_payments,
      can_restore_debts = excluded.can_restore_debts,
      can_view_transactions = excluded.can_view_transactions,
      can_edit_payments = excluded.can_edit_payments,
      can_delete_payments = excluded.can_delete_payments,
      can_view_payment_history = excluded.can_view_payment_history,
      can_manage_collections = excluded.can_manage_collections,
      can_view_financial_reports = excluded.can_view_financial_reports,
      can_export_data = excluded.can_export_data,
      can_import_data = excluded.can_import_data,
      can_manage_receipts = excluded.can_manage_receipts,
      can_create_statements = excluded.can_create_statements,
      can_create_receipts = excluded.can_create_receipts,
      can_edit_receipts = excluded.can_edit_receipts,
      can_delete_receipts = excluded.can_delete_receipts,
      can_export_receipts = excluded.can_export_receipts,
      can_view_report_summary = excluded.can_view_report_summary,
      can_export_reports = excluded.can_export_reports,
      can_send_notifications = excluded.can_send_notifications,
      can_manage_notifications = excluded.can_manage_notifications,
      can_manage_notification_templates = excluded.can_manage_notification_templates,
      can_send_bulk_notifications = excluded.can_send_bulk_notifications,
      can_manage_employees = excluded.can_manage_employees,
      can_view_audit_log = excluded.can_view_audit_log,
      can_manage_backup = excluded.can_manage_backup,
      can_run_manual_backup = excluded.can_run_manual_backup,
      can_restore_backup = excluded.can_restore_backup,
      can_manage_daftar_sync = excluded.can_manage_daftar_sync,
      can_view_sync_logs = excluded.can_view_sync_logs,
      can_retry_failed_sync = excluded.can_retry_failed_sync,
      can_manage_subscription = excluded.can_manage_subscription,
      can_view_dashboard = excluded.can_view_dashboard,
      can_view_recent_activity = excluded.can_view_recent_activity,
      can_view_market_rates = excluded.can_view_market_rates,
      can_manage_market_rate_refresh = excluded.can_manage_market_rate_refresh,
      can_view_intelligence = excluded.can_view_intelligence,
      can_view_expiry = excluded.can_view_expiry,
      can_manage_expiry = excluded.can_manage_expiry,
      can_manage_settings = excluded.can_manage_settings,
      can_manage_security_settings = excluded.can_manage_security_settings,
      can_view_customer_documents = excluded.can_view_customer_documents,
      can_manage_customer_documents = excluded.can_manage_customer_documents,
      can_create_customer_qr = excluded.can_create_customer_qr,
      can_view_customer_qr = excluded.can_view_customer_qr,
      can_archive_customers = excluded.can_archive_customers,
      can_restore_archived_customers = excluded.can_restore_archived_customers,
      can_blacklist_customers = excluded.can_blacklist_customers,
      can_remove_customer_blacklist = excluded.can_remove_customer_blacklist,
      can_approve_new_debts = excluded.can_approve_new_debts,
      can_reject_new_debts = excluded.can_reject_new_debts,
      can_override_debt_limit = excluded.can_override_debt_limit,
      can_change_due_date_after_create = excluded.can_change_due_date_after_create,
      can_close_debts = excluded.can_close_debts,
      can_reopen_debts = excluded.can_reopen_debts,
      can_change_debt_currency = excluded.can_change_debt_currency,
      can_change_debt_amount_after_approval = excluded.can_change_debt_amount_after_approval,
      can_approve_payments = excluded.can_approve_payments,
      can_void_payments = excluded.can_void_payments,
      can_correct_payment_amount = excluded.can_correct_payment_amount,
      can_correct_payment_date = excluded.can_correct_payment_date,
      can_reallocate_payments = excluded.can_reallocate_payments,
      can_restore_voided_payments = excluded.can_restore_voided_payments,
      can_print_receipts = excluded.can_print_receipts,
      can_share_receipts = excluded.can_share_receipts,
      can_reissue_receipts = excluded.can_reissue_receipts,
      can_view_receipt_history = excluded.can_view_receipt_history,
      can_lock_receipts = excluded.can_lock_receipts,
      can_unlock_receipts = excluded.can_unlock_receipts,
      can_suspend_employees = excluded.can_suspend_employees,
      can_reactivate_employees = excluded.can_reactivate_employees,
      can_reset_employee_passwords = excluded.can_reset_employee_passwords,
      can_view_employee_login_history = excluded.can_view_employee_login_history,
      can_force_employee_logout = excluded.can_force_employee_logout,
      can_manage_employee_devices = excluded.can_manage_employee_devices,
      can_pause_sync = excluded.can_pause_sync,
      can_resume_sync = excluded.can_resume_sync,
      can_replay_failed_sync = excluded.can_replay_failed_sync,
      can_view_sync_payloads = excluded.can_view_sync_payloads,
      can_download_backups = excluded.can_download_backups,
      can_export_audit_log = excluded.can_export_audit_log,
      can_view_active_devices = excluded.can_view_active_devices,
      can_remove_trusted_devices = excluded.can_remove_trusted_devices,
      can_approve_new_devices = excluded.can_approve_new_devices,
      can_view_failed_logins = excluded.can_view_failed_logins,
      can_lock_employee_accounts = excluded.can_lock_employee_accounts,
      can_unlock_employee_accounts = excluded.can_unlock_employee_accounts,
      can_force_password_change = excluded.can_force_password_change,
      can_manage_biometric_login = excluded.can_manage_biometric_login,
      can_view_deleted_transactions = excluded.can_view_deleted_transactions,
      can_restore_deleted_transactions = excluded.can_restore_deleted_transactions,
      can_approve_transaction_edits = excluded.can_approve_transaction_edits,
      can_view_transaction_change_history = excluded.can_view_transaction_change_history,
      can_lock_old_transactions = excluded.can_lock_old_transactions,
      can_unlock_old_transactions = excluded.can_unlock_old_transactions,
      can_transfer_transactions_between_customers = excluded.can_transfer_transactions_between_customers,
      can_require_transaction_edit_reason = excluded.can_require_transaction_edit_reason,
      can_view_daily_reports = excluded.can_view_daily_reports,
      can_view_weekly_reports = excluded.can_view_weekly_reports,
      can_view_monthly_reports = excluded.can_view_monthly_reports,
      can_view_yearly_reports = excluded.can_view_yearly_reports,
      can_create_custom_reports = excluded.can_create_custom_reports,
      can_schedule_reports = excluded.can_schedule_reports,
      can_send_report_notifications = excluded.can_send_report_notifications,
      can_view_employee_performance_reports = excluded.can_view_employee_performance_reports,
      can_assign_customer_tags = excluded.can_assign_customer_tags,
      can_manage_customer_tags = excluded.can_manage_customer_tags,
      can_set_customer_priority = excluded.can_set_customer_priority,
      can_set_customer_status = excluded.can_set_customer_status,
      can_create_followups = excluded.can_create_followups,
      can_complete_followups = excluded.can_complete_followups,
      can_view_customer_contact_history = excluded.can_view_customer_contact_history,
      can_add_private_customer_notes = excluded.can_add_private_customer_notes,
      can_view_backend_health = excluded.can_view_backend_health,
      can_view_database_health = excluded.can_view_database_health,
      can_view_sync_queue = excluded.can_view_sync_queue,
      can_clear_cache = excluded.can_clear_cache,
      can_refresh_configuration = excluded.can_refresh_configuration,
      can_view_version_history = excluded.can_view_version_history,
      can_view_feature_flags = excluded.can_view_feature_flags,
      can_manage_feature_flags = excluded.can_manage_feature_flags,
      can_approve_customer_creation = excluded.can_approve_customer_creation,
      can_approve_customer_edits = excluded.can_approve_customer_edits,
      can_approve_customer_deletion = excluded.can_approve_customer_deletion,
      can_approve_debt_edits = excluded.can_approve_debt_edits,
      can_approve_debt_deletion = excluded.can_approve_debt_deletion,
      can_approve_payment_voids = excluded.can_approve_payment_voids,
      can_approve_restores = excluded.can_approve_restores,
      can_approve_debt_limit_changes = excluded.can_approve_debt_limit_changes,
      can_view_full_phone_numbers = excluded.can_view_full_phone_numbers,
      can_view_masked_phone_numbers = excluded.can_view_masked_phone_numbers,
      can_view_identity_documents = excluded.can_view_identity_documents,
      can_download_identity_documents = excluded.can_download_identity_documents,
      can_view_private_notes = excluded.can_view_private_notes,
      can_edit_private_notes = excluded.can_edit_private_notes,
      can_export_personal_data = excluded.can_export_personal_data,
      can_anonymize_customer_data = excluded.can_anonymize_customer_data,
      can_send_sms = excluded.can_send_sms,
      can_send_push_notifications = excluded.can_send_push_notifications,
      can_send_telegram_notifications = excluded.can_send_telegram_notifications,
      can_send_whatsapp_templates = excluded.can_send_whatsapp_templates,
      can_approve_notifications = excluded.can_approve_notifications,
      can_view_notification_delivery_status = excluded.can_view_notification_delivery_status,
      can_retry_failed_notifications = excluded.can_retry_failed_notifications,
      can_lock_bulk_messaging = excluded.can_lock_bulk_messaging,
      can_view_api_status = excluded.can_view_api_status,
      can_manage_api_keys = excluded.can_manage_api_keys,
      can_revoke_api_keys = excluded.can_revoke_api_keys,
      can_view_webhook_logs = excluded.can_view_webhook_logs,
      can_retry_webhooks = excluded.can_retry_webhooks,
      can_disable_integrations = excluded.can_disable_integrations,
      can_enable_integrations = excluded.can_enable_integrations,
      can_view_sync_mappings = excluded.can_view_sync_mappings,
      can_create_automation_rules = excluded.can_create_automation_rules,
      can_edit_automation_rules = excluded.can_edit_automation_rules,
      can_delete_automation_rules = excluded.can_delete_automation_rules,
      can_pause_resume_automation = excluded.can_pause_resume_automation,
      can_view_automation_logs = excluded.can_view_automation_logs,
      can_create_alert_rules = excluded.can_create_alert_rules,
      can_edit_alert_thresholds = excluded.can_edit_alert_thresholds,
      can_mute_alerts = excluded.can_mute_alerts,
      updated_at = now(),
      updated_by = coalesce(auth.uid(), public.employee_permissions.updated_by);
  elsif tg_op = 'UPDATE' and old.role = 'employee' then
    delete from public.employee_permissions where employee_id = old.id;
  end if;

  return new;
end;
$function$;
